### PR TITLE
bump package min versions; more 80-width styling

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
@strengejacke Does this look okay? I think you have already fixed the failing test in the `main` branch.

**Comment by strengejacke** [comment]
When are the two workflows executed?

**Comment by IndrajeetPatil** [comment]
- Testing code coverage and changes in it in PRs
- Checking for lints using `lintr`

**Comment by IndrajeetPatil** [comment]
`lintr` workflow is currently failing because it can't find `M3C` package on `CRAN`.

**Comment by strengejacke** [comment]
> `lintr` workflow is currently failing because it can't find `M3C` package on `CRAN`.

Yeah, that package is on Bioconductor.

**Comment by strengejacke** [comment]
Hm, the workflows should either be fixed or removed, to avoid false positives.

**Comment by IndrajeetPatil** [comment]
I've removed it.

**Comment by strengejacke** [comment]
Same for test-coverage, though it would be great to have this workflow running.

**Comment by strengejacke** [comment]
Maybe you can find a way how to prevent the workflow from quitting when there's a warning? Currently, warnings are converted to errors... Or how to install M3C at the right place.

**Comment by IndrajeetPatil** [comment]
@strengejacke I have reverted all actions related changes, so no idea what is going on now.

**Pull request merged**
