### PR TITLE
replace interaction sep with "x" à la modelsummary

### PR DESCRIPTION
**Pull request by DominiqueMakowski**
Looks better than with the `:`

``` r
parameters::parameters(lm(Sepal.Length ~ Species * Sepal.Width, data = iris))
#> Parameter                          | Coefficient |   SE |        95% CI | t(144) |      p
#> -----------------------------------------------------------------------------------------
#> (Intercept)                        |        2.64 | 0.57 | [ 1.51, 3.77] |   4.62 | < .001
#> Species [versicolor]               |        0.90 | 0.80 | [-0.68, 2.48] |   1.13 | 0.261 
#> Species [virginica]                |        1.27 | 0.82 | [-0.35, 2.88] |   1.55 | 0.123 
#> Sepal Width                        |        0.69 | 0.17 | [ 0.36, 1.02] |   4.17 | < .001
#> Species [versicolor] x Sepal Width |        0.17 | 0.26 | [-0.34, 0.69] |   0.67 | 0.503 
#> Species [virginica] x Sepal Width  |        0.21 | 0.26 | [-0.29, 0.72] |   0.83 | 0.411
#> 
#> Uncertainty intervals (equal-tailed) and p-values (two-tailed) computed
#>   using a Wald t-distribution approximation.
```

<sup>Created on 2022-10-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### CODE REVIEW

**Comment by strengejacke** [comment]
hm, can we make this optional, maybe via `print()`? I'm not 100% convinced that I prefer this style. @easystats/core-team opinions?

**Comment by strengejacke** [comment]
What about this?

``` r
library(parameters)
m <- lm(Sepal.Length ~ Species * Sepal.Width, data = iris)

model_parameters(m)
#> Parameter                          | Coefficient |   SE |        95% CI | t(144) |      p
#> -----------------------------------------------------------------------------------------
#> (Intercept)                        |        2.64 | 0.57 | [ 1.51, 3.77] |   4.62 | < .001
#> Species [versicolor]               |        0.90 | 0.80 | [-0.68, 2.48] |   1.13 | 0.261 
#> Species [virginica]                |        1.27 | 0.82 | [-0.35, 2.88] |   1.55 | 0.123 
#> Sepal Width                        |        0.69 | 0.17 | [ 0.36, 1.02] |   4.17 | < .001
#> Species [versicolor] * Sepal Width |        0.17 | 0.26 | [-0.34, 0.69] |   0.67 | 0.503 
#> Species [virginica] * Sepal Width  |        0.21 | 0.26 | [-0.29, 0.72] |   0.83 | 0.411
#> 
#> Uncertainty intervals (equal-tailed) and p-values (two-tailed) computed
#>   using a Wald t-distribution approximation.

model_parameters(m, interaction_sep = " x ")
#> Parameter                          | Coefficient |   SE |        95% CI | t(144) |      p
#> -----------------------------------------------------------------------------------------
#> (Intercept)                        |        2.64 | 0.57 | [ 1.51, 3.77] |   4.62 | < .001
#> Species [versicolor]               |        0.90 | 0.80 | [-0.68, 2.48] |   1.13 | 0.261 
#> Species [virginica]                |        1.27 | 0.82 | [-0.35, 2.88] |   1.55 | 0.123 
#> Sepal Width                        |        0.69 | 0.17 | [ 0.36, 1.02] |   4.17 | < .001
#> Species [versicolor] x Sepal Width |        0.17 | 0.26 | [-0.34, 0.69] |   0.67 | 0.503 
#> Species [virginica] x Sepal Width  |        0.21 | 0.26 | [-0.29, 0.72] |   0.83 | 0.411
#> 
#> Uncertainty intervals (equal-tailed) and p-values (two-tailed) computed
#>   using a Wald t-distribution approximation.

options(parameters_interaction = "*")
model_parameters(m)
#> Parameter                          | Coefficient |   SE |        95% CI | t(144) |      p
#> -----------------------------------------------------------------------------------------
#> (Intercept)                        |        2.64 | 0.57 | [ 1.51, 3.77] |   4.62 | < .001
#> Species [versicolor]               |        0.90 | 0.80 | [-0.68, 2.48] |   1.13 | 0.261 
#> Species [virginica]                |        1.27 | 0.82 | [-0.35, 2.88] |   1.55 | 0.123 
#> Sepal Width                        |        0.69 | 0.17 | [ 0.36, 1.02] |   4.17 | < .001
#> Species [versicolor] * Sepal Width |        0.17 | 0.26 | [-0.34, 0.69] |   0.67 | 0.503 
#> Species [virginica] * Sepal Width  |        0.21 | 0.26 | [-0.29, 0.72] |   0.83 | 0.411
#> 
#> Uncertainty intervals (equal-tailed) and p-values (two-tailed) computed
#>   using a Wald t-distribution approximation.

options(parameters_interaction = "x")
model_parameters(m)
#> Parameter                          | Coefficient |   SE |        95% CI | t(144) |      p
#> -----------------------------------------------------------------------------------------
#> (Intercept)                        |        2.64 | 0.57 | [ 1.51, 3.77] |   4.62 | < .001
#> Species [versicolor]               |        0.90 | 0.80 | [-0.68, 2.48] |   1.13 | 0.261 
#> Species [virginica]                |        1.27 | 0.82 | [-0.35, 2.88] |   1.55 | 0.123 
#> Sepal Width                        |        0.69 | 0.17 | [ 0.36, 1.02] |   4.17 | < .001
#> Species [versicolor] x Sepal Width |        0.17 | 0.26 | [-0.34, 0.69] |   0.67 | 0.503 
#> Species [virginica] x Sepal Width  |        0.21 | 0.26 | [-0.29, 0.72] |   0.83 | 0.411
#> 
#> Uncertainty intervals (equal-tailed) and p-values (two-tailed) computed
#>   using a Wald t-distribution approximation.

options(parameters_interaction = NULL)
model_parameters(m)
#> Parameter                          | Coefficient |   SE |        95% CI | t(144) |      p
#> -----------------------------------------------------------------------------------------
#> (Intercept)                        |        2.64 | 0.57 | [ 1.51, 3.77] |   4.62 | < .001
#> Species [versicolor]               |        0.90 | 0.80 | [-0.68, 2.48] |   1.13 | 0.261 
#> Species [virginica]                |        1.27 | 0.82 | [-0.35, 2.88] |   1.55 | 0.123 
#> Sepal Width                        |        0.69 | 0.17 | [ 0.36, 1.02] |   4.17 | < .001
#> Species [versicolor] * Sepal Width |        0.17 | 0.26 | [-0.34, 0.69] |   0.67 | 0.503 
#> Species [virginica] * Sepal Width  |        0.21 | 0.26 | [-0.29, 0.72] |   0.83 | 0.411
#> 
#> Uncertainty intervals (equal-tailed) and p-values (two-tailed) computed
#>   using a Wald t-distribution approximation.
```

<sup>Created on 2022-10-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
(we still can change the default, ofcourse)

**Comment by strengejacke** [comment]
damn, I committed the fix for #798 into this PR ^^
Anyway, I think this is safe to merge.

**Comment by strengejacke** [comment]
Let's get back to the default setting later.

**Comment by DominiqueMakowski** [comment]
(it's so much simpler to commit to master 🌈)

**Comment by IndrajeetPatil** [comment]
You mean you don't need to deal with Daniel then 😁

**Comment by bwiernik** [comment]
I am _very_ opposed to the letter x (not a math symbol) or * (not a math symbol, just a keyboard convention, and in R doesn't mean the product but rather the linear terms and the product all combined). 

The times character `\u00d7` × or a colon should be the default in my view.

**Comment by DominiqueMakowski** [comment]
I think "x" (the letter) is a fair ascii proxy of that though, and it looks pretty sleek

**Comment by strengejacke** [comment]
Currently, we use `\u00d7` as default when unicode seems to be supported, else it falls back to `*`, see readme: https://github.com/easystats/parameters

And all who are not satisfied with the defaults (whatever they will be until next release), you can customize a lot:
https://easystats.github.io/parameters/reference/print.parameters_model.html#global-options-to-customize-messages-and-tables-when-printing

**Comment by bwiernik** [comment]
My preference for a default fall back ASCII is a colon

**Comment by rempsyc** [comment]
I agree with bwiernik on this (colon for general consistency within R, else ×)

**Pull request merged**
