### PR TITLE
[Feature] add option for sparse PCA

### PR DESCRIPTION
**Pull request by DominiqueMakowski**
Using https://github.com/erichson/spca

### CODE REVIEW

**Comment by strengejacke** [comment]
You may need to add "rsvd" to the suggested files in DESCRIPTION, too.

**Comment by DominiqueMakowski** [comment]
> You may need to add "rsvd" to the suggested files in DESCRIPTION, too.

why is it?

**Comment by strengejacke** [comment]
> > You may need to add "rsvd" to the suggested files in DESCRIPTION, too.
> 
> why is it?

```
  Error: 
  ! error in pak subprocess
  Caused by error: 
  ! Cannot install packages:
  * deps::.: Can't install dependency sparsepca
  * sparsepca: Can't install dependency rsvd
  * rsvd: Needs R >= 4.0.0
  ```

**Comment by strengejacke** [comment]
and for tests/examples, maybe you also need `requireNamespace("rsvd")`, not sure. Probably adding to suggests will be enough.

**Comment by strengejacke** [comment]
> > > You may need to add "rsvd" to the suggested files in DESCRIPTION, too.
> > 
> > 
> > why is it?
> 
> ```
>   Error: 
>   ! error in pak subprocess
>   Caused by error: 
>   ! Cannot install packages:
>   * deps::.: Can't install dependency sparsepca
>   * sparsepca: Can't install dependency rsvd
>   * rsvd: Needs R >= 4.0.0
> ```

@IndrajeetPatil Do you know why this check still fails? I added rsvd to the workflows.

**Comment by IndrajeetPatil** [comment]
`sparsepca` also needs to be added to ignores. I have done that. So this should be fixed.

**Review by strengejacke — APPROVED** [review]

**Comment by strengejacke** [comment]
oh... please update the NEWS file... 😬

**Comment by IndrajeetPatil** [comment]
Thanks!

**Pull request merged**
