### PR TITLE
`p_value.lme` and `ci_.lme` accept `vcov` argument

### PR DESCRIPTION
**Pull request by vincentarelbundock**
This addresses Issue #681 

Note that the very first commit is a refactor of the test file, but that *all* the original tests are still present and passing. In addition, I added 2 new tests to manually illustrate the computation of p values and standard errors.

### CODE REVIEW

**Review by bwiernik — APPROVED** [review]

**Comment by strengejacke** [comment]
nice, thanks!
Should we add a `dof()` method that returns `model$fixDF[["X"]]`?

**Comment by strengejacke** [comment]
Just saw, no need to change anything, nlme is already captured:

``` r
library(parameters)
library(nlme)
data(iris)
set.seed(1234)
iris$grp <- as.factor(sample(1:3, nrow(iris), replace = TRUE))

# fit example model
model <- lme(
  fixed = Sepal.Length ~ Species * Sepal.Width + Petal.Length,
  random = ~ 1 | grp,
  data = iris
)

degrees_of_freedom(model) # analytical by default
#> [1] 143 143 143 143 143 143 143
degrees_of_freedom(model, "residual") # the original lme-DFs
#> [1] 141 141 141 141 141 141 141
```

<sup>Created on 2022-03-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
> Should we add a `dof()` method that returns `model$fixDF[["X"]]`?

I don't know these models well enough, so I'll defer to your judgement on this.

**Comment by strengejacke** [comment]
I think we're ok with the degrees of freedom, the correct DFs from the model object are extracted also when we use `vcov`:

``` r
library(parameters)
library(nlme)
data(iris)
set.seed(1234)
iris$grp <- as.factor(sample(1:3, nrow(iris), replace = TRUE))

# fit example model
model <- lme(
  fixed = Sepal.Length ~ Species * Sepal.Width + Petal.Length,
  random = ~ 1 | grp,
  data = iris
)

model_parameters(model)
#> # Fixed Effects
#> 
#> Parameter                          | Coefficient |   SE |         95% CI | t(141) |      p
#> ------------------------------------------------------------------------------------------
#> (Intercept)                        |        1.55 | 0.40 | [ 0.76,  2.35] |   3.87 | < .001
#> Species [versicolor]               |        0.41 | 0.55 | [-0.67,  1.50] |   0.75 | 0.454 
#> Species [virginica]                |       -0.41 | 0.58 | [-1.56,  0.74] |  -0.70 | 0.483 
#> Sepal Width                        |        0.66 | 0.11 | [ 0.44,  0.89] |   5.83 | < .001
#> Petal Length                       |        0.82 | 0.07 | [ 0.69,  0.95] |  12.52 | < .001
#> Species [versicolor] * Sepal Width |       -0.48 | 0.19 | [-0.85, -0.12] |  -2.60 | 0.010 
#> Species [virginica] * Sepal Width  |       -0.36 | 0.18 | [-0.71,  0.00] |  -1.99 | 0.048 
#> 
#> # Random Effects
#> 
#> Parameter           | Coefficient
#> ---------------------------------
#> SD (Intercept: grp) |        0.08
#> SD (Residual)       |        0.30
#> 
#> Uncertainty intervals (equal-tailed) and p values (two-tailed) computed using a
#>   Wald t-distribution approximation.

model_parameters(
  model,
  vcov = "vcovCR",
  vcov_args = list(type = "CR1", cluster = iris$grp)
)
#> # Fixed Effects
#> 
#> Parameter                          | Coefficient |   SE |         95% CI | t(141) |      p
#> ------------------------------------------------------------------------------------------
#> (Intercept)                        |        1.55 | 0.40 | [ 0.76,  2.35] |   3.87 | < .001
#> Species [versicolor]               |        0.41 | 0.80 | [-1.17,  1.99] |   0.51 | 0.608 
#> Species [virginica]                |       -0.41 | 0.19 | [-0.78, -0.03] |  -2.15 | 0.033 
#> Sepal Width                        |        0.66 | 0.10 | [ 0.46,  0.86] |   6.64 | < .001
#> Petal Length                       |        0.82 | 0.05 | [ 0.72,  0.91] |  17.27 | < .001
#> Species [versicolor] * Sepal Width |       -0.48 | 0.35 | [-1.18,  0.21] |  -1.37 | 0.172 
#> Species [virginica] * Sepal Width  |       -0.36 | 0.11 | [-0.57, -0.15] |  -3.39 | < .001
#> 
#> # Random Effects
#> 
#> Parameter           | Coefficient
#> ---------------------------------
#> SD (Intercept: grp) |        0.08
#> SD (Residual)       |        0.30
#> 
#> Uncertainty intervals (equal-tailed) and p values (two-tailed) computed using a
#>   Wald t-distribution approximation.
```

**Pull request merged**
