### PR TITLE
[Fix] predict.parameters_efa fixes

### PR DESCRIPTION
**Pull request by DominiqueMakowski**
Added a few tests to hopefully cover most of edgecases.

The code is a bit bulkier and redundant but at least the logic is clear and easy to debut.

### CODE REVIEW

**Review by strengejacke — APPROVED** [review]

**Comment by strengejacke** [comment]
@DominiqueMakowski Is this PR still relevant? There are quite some conflicts that need to be resolved...

**Comment by DominiqueMakowski** [comment]
I'm not sure now, I checked with main and the tests added here do pass so I guess we can close 🤷

**Comment by strengejacke** [comment]
👀 Sometimes, programming remains a mystery...

**Comment by strengejacke** [comment]
Seems like tests in main were not up to date. I added your tests, and they're failing, so probably it still need to be implemented. I added the code to https://github.com/easystats/parameters/pull/921

**Pull request closed without merging**
