### PR TITLE
change `data_set` attribute name for `dataset` (in PCA/EFA)

### PR DESCRIPTION
**Pull request by DominiqueMakowski**
It's just nicer to have it in one word, but is it worth it?

### CODE REVIEW

**Comment by bwiernik** [comment]
The spelling is properly also "dataset" not "data set", so I think the change is good. Changing hidden attributes like this is fine by me

**Review by bwiernik — APPROVED** [review]

**Comment by bwiernik** [comment]
What's going on with the tests?

**Comment by strengejacke** [comment]
I think the file [principal_components.R](https://github.com/easystats/parameters/pull/773/files#diff-265b13b9b35251cccfe6c856f7e36cb243be31ef4021671d2a0863234c879937) has more occurrences of `data_set` that need to be changed.

**Comment by strengejacke** [comment]
Note that this is a breaking change and will cause failures in _performance_. Not sure about other packages.

**Review by strengejacke — APPROVED** [review]

**Pull request merged**
