### PR TITLE
Add `dominance_analysis` function

### PR DESCRIPTION
**Pull request by jluchman**
A transition and extension of PR easystats/performance#411 to `parameters`

One major change from the `performance` version include updates related to display which follows more closely with `parameters`' style in terms of the results returned and display format.  In particular, the first set of dominance statistics are mapped onto the parameters returned by the model to show more clearly how each is associated with dominance statistics mimicking the table of statistics posted in the thread/discussion of the PR to `performance`.  One of the goals of this extension is to link these statistics directly with the returned `model_parameters` results in a future update. 

A second is the addition of more arguments to allow for sets of bound together parameters/predictors in the dominance analysis, to allow for covariates/parameters to remove from the dominance analysis, and the option to pass on quoted arguments when necessary (underlying implementation needs this occasionally to prevent early evaluation of otherwise data masked arguments).

All stylistic changes applied in the `performance` version have been preserved and I have attempted to follow them in updates/transition to the `parameters` package.

### CODE REVIEW

**Comment by strengejacke** [comment]
Looks like this can be merged, will take a closer look the next days. Thanks for the PR!

**Comment by bwiernik** [comment]
Could someone post a reprex of the examples?

**Comment by jluchman** [comment]
@bwiernik, I have posted a reproduced version of the examples for the `dominance_analysis` function below (with the addition of a call to `library(parameters)` from the  `devtools::dev_mode`-created directory on my machine).

```
d> library(parameters)
d> data(mtcars)
d> model <- glm(vs ~ cyl + carb + mpg, data = mtcars, family = binomial())
d> performance::r2(model)
# R2 for Logistic Regression
  Tjur's R2: 0.741
d> dominance_analysis(model)
# Dominance Analysis Results

Model R2 Value:  0.741 

General Dominance Statistics

parameter   | general_dominance | standardized | ranks |   subset
-----------------------------------------------------------------
(Intercept) |                   |              |       | constant
cyl         |             0.366 |        0.493 |     1 |      cyl
carb        |             0.178 |        0.241 |     3 |     carb
mpg         |             0.197 |        0.266 |     2 |      mpg

Conditional Dominance Statistics

subset | IVs_1 | IVs_2 | IVs_3
------------------------------
cyl    | 0.654 | 0.254 | 0.190
carb   | 0.394 | 0.066 | 0.074
mpg    | 0.474 | 0.085 | 0.032

Complete Dominance Designations

subset | < cyl | < carb | < mpg
-------------------------------
cyl    |       |  FALSE | FALSE
carb   |  TRUE |        |      
mpg    |  TRUE |        |      
d> model_wt <- glm(vs ~ cyl + carb + mpg, data = mtcars,
+                      weights = wt, family = binomial())
Warning message:
In eval(family$initialize) : non-integer #successes in a binomial glm!
d> dominance_analysis(model_wt, quote_args = "weights")
# Dominance Analysis Results

Model R2 Value:  0.776 

General Dominance Statistics

parameter   | general_dominance | standardized | ranks |   subset
-----------------------------------------------------------------
(Intercept) |                   |              |       | constant
cyl         |             0.390 |        0.503 |     1 |      cyl
carb        |             0.174 |        0.224 |     3 |     carb
mpg         |             0.212 |        0.273 |     2 |      mpg

Conditional Dominance Statistics

subset | IVs_1 | IVs_2 | IVs_3
------------------------------
cyl    | 0.679 | 0.279 | 0.213
carb   | 0.376 | 0.062 | 0.083
mpg    | 0.496 | 0.100 | 0.039

Complete Dominance Designations

subset | < cyl | < carb | < mpg
-------------------------------
cyl    |       |  FALSE | FALSE
carb   |  TRUE |        |      
mpg    |  TRUE |        |      
```

**Comment by strengejacke** [comment]
I think we should merge this before the next CRAN release, but that should be no big deal. If possible, we wait for https://github.com/glmmTMB/glmmTMB/issues/828, to see whether this affects the new functionality of extracting random effects CIs in `model_parameters()`?

**Comment by strengejacke** [comment]
Thanks a lot! You may want to add yourself as contributor to the DESCRIPTION file?

**Comment by fmg-jluchman** [comment]
Happy to make that update! Most likely will do so tomorrow.

**Comment by bwiernik** [comment]
This looks good to me. Last thing. Can you update the styling on the column headers:

1. Use uppercase (https://easystats.github.io/easystats/articles/conventions.html)
2. Call the "standardized" column "Percent"

Lastly, in the print method, can you convert the underscores in the column names to spaces?

Then we are good to go

**Comment by jluchman** [comment]
Will do - and thanks for pointing me to the coding style conventions!

**Comment by bwiernik** [comment]
I'm not sure why a handful of unrelated tests are failing here. Should i merge anyway @IndrajeetPatil @strengejacke ?

**Comment by IndrajeetPatil** [comment]
@bwiernik The same tests are also failing on the default branch, so those failures are unrelated to the changes in this PR.

If ready, feel free to merge.

**Comment by bwiernik** [comment]
Thanks so much @jluchman!

**Pull request merged**
