### PR TITLE
Improve parameter names cleaning (#685)

### PR DESCRIPTION
**Pull request by strengejacke**
This PR adds columns Level and Group when `group_level = TRUE`.

### CODE REVIEW

**Comment by strengejacke** [comment]
@DominiqueMakowski Can you test this PR for some models and check if it works for you as intended?

**Comment by DominiqueMakowski** [comment]
The Group and Level columns are present as expected. But their content differs a bit between lme4 and brms for instance (probably due to the regex?)


### lme4 (the gold standard)
``` r
data <- lme4::sleepstudy

model <- lme4::lmer(Reaction ~ Days + (1 + Days| Subject), data = data)
random <- modelbased::estimate_grouplevel(model)

head(as.data.frame(random))
#>     Group Level   Parameter Coefficient        SE   CI     CI_low    CI_high
#> 1 Subject   308 (Intercept)    2.258551 12.070857 0.95 -21.399894  25.916996
#> 2 Subject   308        Days    9.198976  2.304839 0.95   4.681574  13.716377
#> 3 Subject   309 (Intercept)  -40.398738 12.070857 0.95 -64.057183 -16.740293
#> 4 Subject   309        Days   -8.619681  2.304839 0.95 -13.137082  -4.102279
#> 5 Subject   310 (Intercept)  -38.960409 12.070857 0.95 -62.618854 -15.301964
#> 6 Subject   310        Days   -5.448856  2.304839 0.95  -9.966258  -0.931455

unique(random$Group)
#> [1] "Subject"
unique(random$Level)
#>  [1] "308" "309" "310" "330" "331" "332" "333" "334" "335" "337" "349" "350"
#> [13] "351" "352" "369" "370" "371" "372"
unique(random$Parameter)
#> [1] "(Intercept)" "Days"
```
Everything is as expected and clean, the Level are the factor levels and the parameters are the parameters.


```r
model <- brms::brm(Reaction ~ Days + (1 + Days | Subject), data = data, refresh = 0, algorithm = "meanfield")
random <- modelbased::estimate_grouplevel(model)

head(as.data.frame(random))
#>           Group       Level           Parameter   Component   Median   CI
#> 1 Days: Subject Subject.308 r_Subject[308,Days] conditional 24.11695 0.95
#> 2 Days: Subject Subject.309 r_Subject[309,Days] conditional 17.88615 0.95
#> 3 Days: Subject Subject.310 r_Subject[310,Days] conditional 19.39995 0.95
#> 4 Days: Subject Subject.330 r_Subject[330,Days] conditional 24.53375 0.95
#> 5 Days: Subject Subject.331 r_Subject[331,Days] conditional 24.84935 0.95
#> 6 Days: Subject Subject.332 r_Subject[332,Days] conditional 25.14070 0.95
#>    CI_low CI_high pd ROPE_Percentage     Khat
#> 1 3.11556 72.6206  1     0.012618297 36.78657
#> 2 2.87148 53.5931  1     0.043112513 36.93645
#> 3 1.56291 56.7510  1     0.041009464 36.99276
#> 4 4.01403 71.1091  1     0.010515247 37.02471
#> 5 4.07703 76.1817  1     0.008412198 36.90496
#> 6 4.06189 74.2409  1     0.011566772 37.23342

unique(random$Group)
#> [1] "Days: Subject"      "Intercept: Subject" "SD/Cor: Subject"
```
Here the Group name include the random factor, which makes sense, but seems a bit messy (?) (I am gonna make another example with 2 random factors to see how lme4 behaves)

```r
unique(random$Level)
#>  [1] "Subject.308"      "Subject.309"      "Subject.310"      "Subject.330"     
#>  [5] "Subject.331"      "Subject.332"      "Subject.333"      "Subject.334"     
#>  [9] "Subject.335"      "Subject.337"      "Subject.349"      "Subject.350"     
#> [13] "Subject.351"      "Subject.352"      "Subject.369"      "Subject.370"     
#> [17] "Subject.371"      "Subject.372"      "(Intercept)"      "Days"            
#> [21] "Intercept ~ Days"
```
If Group == Subject, then the Level should correspond to the corresponding factor levels i.e., without the column name.

```r
unique(random$Parameter)
#>  [1] "r_Subject[308,Days]"          "r_Subject[309,Days]"         
#>  [3] "r_Subject[310,Days]"          "r_Subject[330,Days]"         
#>  [5] "r_Subject[331,Days]"          "r_Subject[332,Days]"         
#>  [7] "r_Subject[333,Days]"          "r_Subject[334,Days]"         
#>  [9] "r_Subject[335,Days]"          "r_Subject[337,Days]"         
#> [11] "r_Subject[349,Days]"          "r_Subject[350,Days]"         
#> [13] "r_Subject[351,Days]"          "r_Subject[352,Days]"         
#> [15] "r_Subject[369,Days]"          "r_Subject[370,Days]"         
#> [17] "r_Subject[371,Days]"          "r_Subject[372,Days]"         
#> [19] "r_Subject[308,Intercept]"     "r_Subject[309,Intercept]"    
#> [21] "r_Subject[310,Intercept]"     "r_Subject[330,Intercept]"    
#> [23] "r_Subject[331,Intercept]"     "r_Subject[332,Intercept]"    
#> [25] "r_Subject[333,Intercept]"     "r_Subject[334,Intercept]"    
#> [27] "r_Subject[335,Intercept]"     "r_Subject[337,Intercept]"    
#> [29] "r_Subject[349,Intercept]"     "r_Subject[350,Intercept]"    
#> [31] "r_Subject[351,Intercept]"     "r_Subject[352,Intercept]"    
#> [33] "r_Subject[369,Intercept]"     "r_Subject[370,Intercept]"    
#> [35] "r_Subject[371,Intercept]"     "r_Subject[372,Intercept]"    
#> [37] "sd_Subject__Intercept"        "sd_Subject__Days"            
#> [39] "cor_Subject__Intercept__Days"
```

This one gives the details


<sup>Created on 2022-03-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DominiqueMakowski** [comment]
### 2 random factors

``` r
data <- lme4::sleepstudy
data$Fac2 <- rep(c("A", "B"), length.out = nrow(data))

model <- lme4::lmer(Reaction ~ Days + (1 + Days| Subject) + (1 + Days| Fac2), data = data)
#> boundary (singular) fit: see ?isSingular
random <- modelbased::estimate_grouplevel(model)

head(as.data.frame(random)[1:4])
#>     Group Level   Parameter   Coefficient
#> 1    Fac2     A (Intercept) -7.131812e-06
#> 2    Fac2     A        Days  4.648827e-07
#> 3    Fac2     B (Intercept)  7.131812e-06
#> 4    Fac2     B        Days -4.648827e-07
#> 5 Subject   308 (Intercept)  2.256886e+00
#> 6 Subject   308        Days  9.199185e+00
unique(random$Group)
#> [1] "Fac2"    "Subject"
unique(random$Level)
#>  [1] "A"   "B"   "308" "309" "310" "330" "331" "332" "333" "334" "335" "337"
#> [13] "349" "350" "351" "352" "369" "370" "371" "372"
unique(random$Parameter)
#> [1] "(Intercept)" "Days"
```

```r
model <- brms::brm(Reaction ~ Days + (1 + Days | Subject) + (1 + Days| Fac2), data = data, refresh = 0, algorithm = "meanfield")
random <- modelbased::estimate_grouplevel(model)

head(as.data.frame(random)[1:4])
#>           Group       Level           Parameter   Component
#> 1    Days: Fac2      Fac2.A      r_Fac2[A,Days] conditional
#> 2    Days: Fac2      Fac2.B      r_Fac2[B,Days] conditional
#> 3 Days: Subject Subject.308 r_Subject[308,Days] conditional
#> 4 Days: Subject Subject.309 r_Subject[309,Days] conditional
#> 5 Days: Subject Subject.310 r_Subject[310,Days] conditional
#> 6 Days: Subject Subject.330 r_Subject[330,Days] conditional
unique(random$Group)
#> [1] "Days: Fac2"         "Days: Subject"      "Intercept: Fac2"   
#> [4] "Intercept: Subject" "SD/Cor: Fac2"       "SD/Cor: Subject"
unique(random$Level)
#>  [1] "Fac2.A"           "Fac2.B"           "Subject.308"      "Subject.309"     
#>  [5] "Subject.310"      "Subject.330"      "Subject.331"      "Subject.332"     
#>  [9] "Subject.333"      "Subject.334"      "Subject.335"      "Subject.337"     
#> [13] "Subject.349"      "Subject.350"      "Subject.351"      "Subject.352"     
#> [17] "Subject.369"      "Subject.370"      "Subject.371"      "Subject.372"     
#> [21] "(Intercept)"      "Days"             "Intercept ~ Days"
unique(random$Parameter)
#>  [1] "r_Fac2[A,Days]"               "r_Fac2[B,Days]"              
#>  [3] "r_Subject[308,Days]"          "r_Subject[309,Days]"         
#>  [5] "r_Subject[310,Days]"          "r_Subject[330,Days]"         
#>  [7] "r_Subject[331,Days]"          "r_Subject[332,Days]"         
#>  [9] "r_Subject[333,Days]"          "r_Subject[334,Days]"         
#> [11] "r_Subject[335,Days]"          "r_Subject[337,Days]"         
#> [13] "r_Subject[349,Days]"          "r_Subject[350,Days]"         
#> [15] "r_Subject[351,Days]"          "r_Subject[352,Days]"         
#> [17] "r_Subject[369,Days]"          "r_Subject[370,Days]"         
#> [19] "r_Subject[371,Days]"          "r_Subject[372,Days]"         
#> [21] "r_Fac2[A,Intercept]"          "r_Fac2[B,Intercept]"         
#> [23] "r_Subject[308,Intercept]"     "r_Subject[309,Intercept]"    
#> [25] "r_Subject[310,Intercept]"     "r_Subject[330,Intercept]"    
#> [27] "r_Subject[331,Intercept]"     "r_Subject[332,Intercept]"    
#> [29] "r_Subject[333,Intercept]"     "r_Subject[334,Intercept]"    
#> [31] "r_Subject[335,Intercept]"     "r_Subject[337,Intercept]"    
#> [33] "r_Subject[349,Intercept]"     "r_Subject[350,Intercept]"    
#> [35] "r_Subject[351,Intercept]"     "r_Subject[352,Intercept]"    
#> [37] "r_Subject[369,Intercept]"     "r_Subject[370,Intercept]"    
#> [39] "r_Subject[371,Intercept]"     "r_Subject[372,Intercept]"    
#> [41] "sd_Fac2__Intercept"           "sd_Fac2__Days"               
#> [43] "cor_Fac2__Intercept__Days"    "sd_Subject__Intercept"       
#> [45] "sd_Subject__Days"             "cor_Subject__Intercept__Days"
```

<sup>Created on 2022-03-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

It's all there, but the presentation is somewhat less clean (of course, we cannot fully match lme4 as brms can have much more complex specifications, so idk how we can clean the random effect segmentation in an easy yet safe way 🤔

**Comment by strengejacke** [comment]
Is it ok if the columns for `as.data.frame()` are named `Groupname` and `Level`?

**Comment by mattansb** [comment]
> Is it ok if the columns for as.data.frame() are named Groupname and Level?

What were they named before?

**Comment by strengejacke** [comment]
I changed it, names are now identical, the former values for Group are now stored in Groupname. Thus, Group/Level should now match between Bayes and Freq, when using `model_parameters() |> as.data.frame()`

**Comment by strengejacke** [comment]
``` r
library(parameters)
library(brms)
#> Loading required package: Rcpp
#> Loading 'brms' package (version 2.16.3). Useful instructions
#> can be found by typing help('brms'). A more detailed introduction
#> to the package is available through vignette('brms_overview').
#> 
#> Attaching package: 'brms'
#> The following object is masked from 'package:stats':
#> 
#>     ar
m4 <- insight::download_model("brms_zi_3")

model_parameters(m4, effects = "all", group_level = TRUE)
#> Warning: Could not estimate a good default ROPE range. Using 'c(-0.1, 0.1)'.
#> # Fixed effects (conditional)
#> 
#> Parameter   | Median |         95% CI |     pd | % in ROPE |  Rhat |    ESS
#> ---------------------------------------------------------------------------
#> (Intercept) |   0.96 | [-0.64,  2.74] | 90.00% |     2.51% | 1.011 | 110.00
#> child       |  -1.16 | [-1.39, -0.97] |   100% |        0% | 0.996 | 278.00
#> camper      |   0.73 | [ 0.51,  0.89] |   100% |        0% | 0.996 | 271.00
#> 
#> # Random effects (conditional)
#> 
#> Parameter   | Median |       95% CI |   pd | % in ROPE |  Rhat |    ESS
#> -----------------------------------------------------------------------
#> (Intercept) |   1.42 | [0.60, 3.07] | 100% |        0% | 1.010 | 126.00
#> 
#> # Fixed effects (zero-inflated)
#> 
#> Parameter   | Median |         95% CI |     pd | % in ROPE |  Rhat |    ESS
#> ---------------------------------------------------------------------------
#> (Intercept) |  -0.48 | [-1.75,  1.16] | 78.00% |    10.46% | 0.997 | 138.00
#> child       |   1.85 | [ 1.28,  2.61] |   100% |        0% | 0.996 | 303.00
#> camper      |  -0.88 | [-1.61, -0.04] | 98.40% |     1.67% | 0.996 | 292.00
#> 
#> # Random effects (zero-inflated)
#> 
#> Parameter   | Median |       95% CI |   pd | % in ROPE |  Rhat |    ESS
#> -----------------------------------------------------------------------
#> (Intercept) |   1.30 | [0.47, 2.90] | 100% |        0% | 0.996 | 129.00
#> 
#> # Random effects (conditional) persons
#> 
#> Parameter |    Median |        95% CI |     pd | % in ROPE |  Rhat |    ESS
#> ---------------------------------------------------------------------------
#> persons.1 |     -0.99 | [-2.71, 0.78] | 92.00% |     2.09% | 1.007 | 106.00
#> persons.2 | -4.65e-03 | [-1.73, 1.54] | 50.00% |    13.81% | 1.013 | 109.00
#> persons.3 |      0.69 | [-1.06, 2.28] | 79.60% |     5.02% | 1.010 | 114.00
#> persons.4 |      1.57 | [-0.22, 3.12] | 96.80% |     2.09% | 1.009 | 114.00
#> 
#> # Random effects (zero-inflated) persons
#> 
#> Parameter | Median |         95% CI |     pd | % in ROPE |  Rhat |    ESS
#> -------------------------------------------------------------------------
#> persons.1 |   1.10 | [-0.29,  2.73] | 94.80% |     3.35% | 0.997 | 166.00
#> persons.2 |   0.18 | [-0.94,  1.60] | 63.20% |    14.64% | 0.996 | 154.00
#> persons.3 |  -0.30 | [-1.54,  1.17] | 64.00% |    12.13% | 0.997 | 154.00
#> persons.4 |  -1.45 | [-3.03, -0.13] | 98.00% |        0% | 1.000 | 189.00
#> 
#> Uncertainty intervals (highest-density) and p-values (two-tailed) computed
#>   using a MCMC distribution approximation.

model_parameters(m4, effects = "all", group_level = TRUE) |> as.data.frame()
#> Warning: Could not estimate a good default ROPE range. Using 'c(-0.1, 0.1)'.
#>                     Parameter Effects     Component       Median   CI
#> 1                 b_Intercept   fixed   conditional  0.962122935 0.95
#> 2                     b_child   fixed   conditional -1.158914429 0.95
#> 3                    b_camper   fixed   conditional  0.725334951 0.95
#> 4      r_persons[1,Intercept]  random   conditional -0.990140635 0.95
#> 5      r_persons[2,Intercept]  random   conditional -0.004651465 0.95
#> 6      r_persons[3,Intercept]  random   conditional  0.693220966 0.95
#> 7      r_persons[4,Intercept]  random   conditional  1.574455375 0.95
#> 8       sd_persons__Intercept  random   conditional  1.421504763 0.95
#> 9              b_zi_Intercept   fixed zero_inflated -0.479537282 0.95
#> 10                 b_zi_child   fixed zero_inflated  1.850482381 0.95
#> 11                b_zi_camper   fixed zero_inflated -0.882974158 0.95
#> 12 r_persons__zi[1,Intercept]  random zero_inflated  1.096158634 0.95
#> 13 r_persons__zi[2,Intercept]  random zero_inflated  0.183185688 0.95
#> 14 r_persons__zi[3,Intercept]  random zero_inflated -0.300752056 0.95
#> 15 r_persons__zi[4,Intercept]  random zero_inflated -1.452137999 0.95
#> 16   sd_persons__zi_Intercept  random zero_inflated  1.303263465 0.95
#>        CI_low     CI_high    pd ROPE_Percentage      Rhat      ESS   Group
#> 1  -0.6352876  2.73751485 0.900      0.02510460 1.0108953 109.6797        
#> 2  -1.3891589 -0.97362269 1.000      0.00000000 0.9959959 278.1606        
#> 3   0.5118781  0.88897733 1.000      0.00000000 0.9961756 271.1664        
#> 4  -2.7050359  0.77571482 0.920      0.02092050 1.0066860 105.6793 persons
#> 5  -1.7330323  1.53630948 0.500      0.13807531 1.0126414 108.9422 persons
#> 6  -1.0596497  2.28372946 0.796      0.05020921 1.0097199 113.7905 persons
#> 7  -0.2200283  3.11756033 0.968      0.02092050 1.0094368 113.6757 persons
#> 8   0.5952264  3.06546891 1.000      0.00000000 1.0098617 126.4138        
#> 9  -1.7506423  1.15939956 0.780      0.10460251 0.9969590 137.6955        
#> 10  1.2761919  2.61467767 1.000      0.00000000 0.9961103 302.7351        
#> 11 -1.6080078 -0.04322698 0.984      0.01673640 0.9959921 292.4991        
#> 12 -0.2906694  2.72573345 0.948      0.03347280 0.9973807 166.2623 persons
#> 13 -0.9434305  1.59661981 0.632      0.14644351 0.9963686 153.9647 persons
#> 14 -1.5367048  1.17031657 0.640      0.12133891 0.9969805 153.7928 persons
#> 15 -3.0285849 -0.13400646 0.980      0.00000000 0.9999921 189.3015 persons
#> 16  0.4666968  2.90202323 1.000      0.00000000 0.9959927 129.1243        
#>             Groupname Level
#> 1                      <NA>
#> 2                      <NA>
#> 3                      <NA>
#> 4  Intercept: persons     1
#> 5  Intercept: persons     2
#> 6  Intercept: persons     3
#> 7  Intercept: persons     4
#> 8     SD/Cor: persons  <NA>
#> 9                      <NA>
#> 10                     <NA>
#> 11                     <NA>
#> 12 Intercept: persons     1
#> 13 Intercept: persons     2
#> 14 Intercept: persons     3
#> 15 Intercept: persons     4
#> 16    SD/Cor: persons  <NA>
```

<sup>Created on 2022-03-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DominiqueMakowski** [comment]
``` r
data <- lme4::sleepstudy
data$Fac2 <- rep(c("A", "B"), length.out = nrow(data))

model <- lme4::lmer(Reaction ~ Days + (1 + Days| Subject) + (1 + Days| Fac2), data = data)
random <- modelbased::estimate_grouplevel(model)

as.data.frame(random)[1:10, 1:3]
#>      Group Level   Parameter
#> 1     Fac2     A (Intercept)
#> 2     Fac2     A        Days
#> 3     Fac2     B (Intercept)
#> 4     Fac2     B        Days
#> 5  Subject   308 (Intercept)
#> 6  Subject   308        Days
#> 7  Subject   309 (Intercept)
#> 8  Subject   309        Days
#> 9  Subject   310 (Intercept)
#> 10 Subject   310        Days


model <- brms::brm(Reaction ~ Days + (1 + Days | Subject), data = data, refresh = 0, algorithm = "meanfield")
random <- modelbased::estimate_grouplevel(model)

as.data.frame(random)[1:10, c("Group", "Level", "Parameter" , "Component", "Groupname")]
#>      Group Level                    Parameter   Component          Groupname
#> 1           <NA> cor_Subject__Intercept__Days conditional    SD/Cor: Subject
#> 2           <NA>             sd_Subject__Days conditional    SD/Cor: Subject
#> 3           <NA>        sd_Subject__Intercept conditional    SD/Cor: Subject
#> 4  Subject   308          r_Subject[308,Days] conditional      Days: Subject
#> 5  Subject   308     r_Subject[308,Intercept] conditional Intercept: Subject
#> 6  Subject   309          r_Subject[309,Days] conditional      Days: Subject
#> 7  Subject   309     r_Subject[309,Intercept] conditional Intercept: Subject
#> 8  Subject   310          r_Subject[310,Days] conditional      Days: Subject
#> 9  Subject   310     r_Subject[310,Intercept] conditional Intercept: Subject
#> 10 Subject   330          r_Subject[330,Days] conditional      Days: Subject
```

<sup>Created on 2022-03-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Thanks Daniel!!  I know you hate regex as much as I do so 🤟 to you ☺️ 

To make it even more easy to use, I feel like `Parameter` should also match where applicable.  

Basically, I would:

1) Swap Parameter with `Parameter`, `Groupname`: "Parameter" corresponds to the Parameter (which "effect" is modelled; Days, Intercept etc, SD/Cor etc), and "Groupname" would be the raw brms label.
2) I'd rename `Groupname` for `Label` or `Name` or `Detail` (to highlight that it refers to the full-raw-brms name)
3) Group should also include the Group for additional parameters like SD/Cor

This would correspond to an output like that:

```r
#>      Group   Level            Parameter                         Detail
#> 1  Subject   NA                       Cor   cor_Subject__Intercept__Days
#> 2  Subject   NA                       SD             sd_Subject__Days
#> 3  Subject   NA                       SD          sd_Subject__Intercept
#> 4  Subject   308                   Days            r_Subject[308,Days] 
#> 5  Subject   308           (Intercept)     r_Subject[308,Intercept]
#> 6  Subject   309                   Days             r_Subject[309,Days]
#> 7  Subject   309           (Intercept)      r_Subject[309,Intercept]
#> 8  Subject   310                   Days            r_Subject[310,Days] 
#> 9  Subject   310           (Intercept)    r_Subject[310,Intercept]
#> 10 Subject   330                   Days            r_Subject[330,Days]
```

It's the closest I think to the statistical meaning, the Group is the random "Group", the Level is the level of that group, the Parameter is what is modelled

**Comment by DominiqueMakowski** [comment]
However I wonder about the 3 first lines, I think it would be more correct like that, if I'm not mistaken:

``` r
data.frame(
  Group = c("Subject", "Subject", "Subject", "Subject", "Subject", "Subject", "Subject", "Subject", "Subject", "Subject"), 
  Level = c(NA, NA,  NA, "308", "308", "309", "309", "310", "310", "330"), 
  Parameter = c("Intercept_Days", "Days", "(Intercept)", "Days", "(Intercept)", "Days", "(Intercept)", "Days", "(Intercept)", "Days"), 
  Component = c("cor", "SD", "SD", "conditional", "conditional", "conditional", "conditional", "conditional", "conditional", "conditional"), 
  Groupname = c("cor_Subject__Intercept__Days", "sd_Subject__Days", "sd_Subject__Intercept", "r_Subject[308,Days]", "r_Subject[308,Intercept]", "r_Subject[309,Days]", "r_Subject[309,Intercept]", "r_Subject[310,Days]", "r_Subject[310,Intercept]", "r_Subject[330,Days]")
  )
#>      Group Level      Parameter   Component                    Groupname
#> 1  Subject  <NA> Intercept_Days         cor cor_Subject__Intercept__Days
#> 2  Subject  <NA>           Days          SD             sd_Subject__Days
#> 3  Subject  <NA>    (Intercept)          SD        sd_Subject__Intercept
#> 4  Subject   308           Days conditional          r_Subject[308,Days]
#> 5  Subject   308    (Intercept) conditional     r_Subject[308,Intercept]
#> 6  Subject   309           Days conditional          r_Subject[309,Days]
#> 7  Subject   309    (Intercept) conditional     r_Subject[309,Intercept]
#> 8  Subject   310           Days conditional          r_Subject[310,Days]
#> 9  Subject   310    (Intercept) conditional     r_Subject[310,Intercept]
#> 10 Subject   330           Days conditional          r_Subject[330,Days]
```

<sup>Created on 2022-03-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


- **Group** is the random group, the (1|**Group**)
- **Level** is the specific level of that Group
- **Component** is the "type" of effect 
- **Parameter** is the effect that is modelled. For Component == `cor`, if I'm not mistaken it's a correlation between other parameters, hence the parameter should indicates the parameters over the which the correlation is estimated?


@mattansb @bwiernik thoughts?

brms is so powerful that it's a challenge to "make it more easy" (to understand), but I think if we'd manage to do this, even a bit, it would be super helpful fo many users and applications!

**Comment by DominiqueMakowski** [comment]
Regarding the regex, it seems like, first thing is the component `r_`, `cor_`, `sd_`, the comes the Group. For `r_`, the Level and Parameter are between square brackets, for `sd_`, Parameter at the end, and for `cor_`, all the Parameters are "the Parameter" (cos it's the correlation between them)

- r_: `"Component_Group[Level, Parameter]"` 
- sd_: `"Component_Group__Parameter*"`
- cor_: `"Component_Group__Parameter*"`

**Comment by strengejacke** [comment]
- `Parameter` is the name of the parameter and matches exactly brms-specification, so this should not be changed. This is what is done in the `format()` and `print()` method. You can fully recover this information from the columns `Group`, `Level`, `Effect` and `Component`.
- `Groupname` is actually redundant now, we have those information in `Group` and `Level`, to match Freq models
- `Component` and `Effects` relate to the model component, i.e. conditional/zero-infl/auxiliary and either random or fixed effects. But these columns have a long tradition in _easystats_, so I wouldn't change anything here.

**Comment by DominiqueMakowski** [comment]
mmh I see, perhaps you're right, perhaps this reformatting/clean-up/uniformization should happen directly in modelbased::estinate_grouplevel

**Comment by strengejacke** [comment]
I think the only thing that could be improved is that SD/Cor are in the component `"random"`. This _could_ probably be `"auxiliary"` or something else, otherwise, it's a bit more a hassle to extract this information. However, this is still available in `"Grouplabel"`.

``` r
library(parameters)
library(brms)
#> Loading required package: Rcpp
#> Loading 'brms' package (version 2.16.3). Useful instructions
#> can be found by typing help('brms'). A more detailed introduction
#> to the package is available through vignette('brms_overview').
#> 
#> Attaching package: 'brms'
#> The following object is masked from 'package:stats':
#> 
#>     ar
m4 <- insight::download_model("brms_zi_3")

model_parameters(m4, effects = "all", group_level = TRUE, component = "all") |> 
  as.data.frame() |> 
  datawizard::data_extract(select = c(1:3, 12:14))
#> Warning: Could not estimate a good default ROPE range. Using 'c(-0.1, 0.1)'.
#>                     Parameter Effects     Component   Group         Grouplabel
#> 1                 b_Intercept   fixed   conditional                           
#> 2                     b_child   fixed   conditional                           
#> 3                    b_camper   fixed   conditional                           
#> 4      r_persons[1,Intercept]  random   conditional persons Intercept: persons
#> 5      r_persons[2,Intercept]  random   conditional persons Intercept: persons
#> 6      r_persons[3,Intercept]  random   conditional persons Intercept: persons
#> 7      r_persons[4,Intercept]  random   conditional persons Intercept: persons
#> 8       sd_persons__Intercept  random   conditional persons    SD/Cor: persons
#> 9              b_zi_Intercept   fixed zero_inflated                           
#> 10                 b_zi_child   fixed zero_inflated                           
#> 11                b_zi_camper   fixed zero_inflated                           
#> 12 r_persons__zi[1,Intercept]  random zero_inflated persons Intercept: persons
#> 13 r_persons__zi[2,Intercept]  random zero_inflated persons Intercept: persons
#> 14 r_persons__zi[3,Intercept]  random zero_inflated persons Intercept: persons
#> 15 r_persons__zi[4,Intercept]  random zero_inflated persons Intercept: persons
#> 16   sd_persons__zi_Intercept  random zero_inflated persons    SD/Cor: persons
#>    Level
#> 1   <NA>
#> 2   <NA>
#> 3   <NA>
#> 4      1
#> 5      2
#> 6      3
#> 7      4
#> 8   <NA>
#> 9   <NA>
#> 10  <NA>
#> 11  <NA>
#> 12     1
#> 13     2
#> 14     3
#> 15     4
#> 16  <NA>
```

<sup>Created on 2022-03-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
I think this could probably be done without much pain, because we have all the regex-stuff in `insight::clean_parameters()`. The only thing is that making changes there will break all printing-functions, and probably some other as well, so I'm hesitant to touch this. ;-)

**Comment by DominiqueMakowski** [comment]
Up to you! I am okay with both ways :)

**Comment by DominiqueMakowski** [comment]
Even though it might be worth to do it in clean_parameters, we could have an "experimental=FALSE" argument and we turn it on little by little and see where it breaks

**Comment by strengejacke** [comment]
or just a new function with a different name,

**Comment by DominiqueMakowski** [comment]
`clean_random()` ? `clean_brms()` ?

**Comment by bwiernik** [comment]
brms and other models are also inconsistent with how factors are cleaned in parameter names

**Comment by bwiernik** [comment]
That's a good idea

**Comment by strengejacke** [comment]
@DominiqueMakowski You can install latest insight from GitHub, and use `clean_parameters(brmsmodel, version = 2)`, which should give the "new" columns and labelling.

**Comment by strengejacke** [comment]
I think we should focus on `clean_parameters()` to do the necessary work. That means in _parameters_, I would revise the format methods for Stan models. This makes this PR redundant.

**Pull request closed without merging**
