### PR TITLE
moving all the `check_*` functions to `{performance}` #581

### LINKED ISSUE #581: moving all the `check_*` functions to `{performance}`
> we've moved all the check_* functions to {performance} even when they didn't really have anything to do with evaluating fit or model adequacy

A few still remain, and we need to decide if we want to make this breaking change (moving them to `{performance}`) for the next release itself:

image

_Originally posted by @IndrajeetPatil in https://github.com/easystats/parameters/issues/578#issuecomment-896623862_

### PR DESCRIPTION
**Pull request by strengejacke**
close #581

Waiting for

- [ ] https://github.com/LudvigOlsen/cvms/pull/29
- [x] https://github.com/jasonmoy28/psycModel/issues/12
- [x] Fix pkgdown build failures

to be resolved.

### CODE REVIEW

**Comment by strengejacke** [comment]
# cvms

<details>

* Version: 1.3.5
* GitHub: https://github.com/ludvigolsen/cvms
* Source code: https://github.com/cran/cvms
* Date/Publication: 2022-08-26 13:54:39 UTC
* Number of recursive dependencies: 144

Run `revdep_details(, "cvms")` for more info

</details>

## Newly broken

*   checking tests ...
    ```
      Running 'testthat.R'
     ERROR
    Running the tests in 'tests/testthat.R' failed.
    Last 13 lines of output:
      CV$Coefficients not equal to list(...).
      Component 1: Attributes: < Names: 12 string mismatches >
      Component 1: Attributes: < Length mismatch: comparison on first 36 components >
      Component 1: Attributes: < Component 26: Modes: character, logical >
      Component 1: Attributes: < Component 26: Lengths: 2, 1 >
      Component 1: Attributes: < Component 26: names for target but not for current >
      Component 1: Attributes: < Component 26: target is character, current is logical >
      Component 1: Attributes: < Component 27: Modes: logical, numeric >
      Component 1: Attributes: < Component 27: target is logical, current is numeric >
      Component 1: Attributes: < Component 28: Modes: numeric, logical >
      ...
      
      [ FAIL 1 | WARN 0 | SKIP 70 | PASS 3622 ]
      Error: Test failures
      Execution halted
    ```

# performance

<details>

* Version: 0.9.2
* GitHub: https://github.com/easystats/performance
* Source code: https://github.com/cran/performance
* Date/Publication: 2022-08-10 11:50:01 UTC
* Number of recursive dependencies: 247

Run `revdep_details(, "performance")` for more info

</details>

## Newly broken

*   checking examples ... ERROR
    ```
    Running examples in 'performance-Ex.R' failed
    The error most likely occurred in:
    
    > ### Name: check_itemscale
    > ### Title: Describe Properties of Item Scales
    > ### Aliases: check_itemscale
    > 
    > ### ** Examples
    > 
    > # data generation from '?prcomp', slightly modified
    ...
    +   pca <- principal_components(as.data.frame(Z), rotation = "varimax", n = 3)
    +   pca
    +   check_itemscale(pca)
    + }
    Loading required package: parameters
    Loading required package: psych
    Warning: `x` needs to be a data frame or matrix.
    Error in apply(x, 2, fun.diff.ideal) : dim(X) must have a positive length
    Calls: check_itemscale ... lapply -> FUN -> data.frame -> item_difficulty -> apply
    Execution halted
    ```

# psycModel

<details>

* Version: 0.4.0
* GitHub: NA
* Source code: https://github.com/cran/psycModel
* Date/Publication: 2022-08-29 15:50:02 UTC
* Number of recursive dependencies: 175

Run `revdep_details(, "psycModel")` for more info

</details>

## Newly broken

*   checking examples ... ERROR
    ```
    Running examples in 'psycModel-Ex.R' failed
    The error most likely occurred in:
    
    > ### Name: efa_summary
    > ### Title: Exploratory Factor Analysis
    > ### Aliases: efa_summary
    > 
    > ### ** Examples
    > 
    > efa_summary(lavaan::HolzingerSwineford1939, starts_with("x"), post_hoc_cfa = TRUE)
    Error: 'check_factorstructure' is not an exported object from 'namespace:parameters'
    Execution halted
    ```

*   checking dependencies in R code ... WARNING
    ```
    Namespaces in Imports field not imported from:
      'lifecycle' 'patchwork'
      All declared Imports should be used.
    Missing or unexported object: 'parameters::check_factorstructure'
    ```

## Newly fixed

*   checking dependencies in R code ... NOTE
    ```
    Namespaces in Imports field not imported from:
      'lifecycle' 'patchwork'
      All declared Imports should be used.
    ```

**Comment by IndrajeetPatil** [comment]
_cvms_ error is likely to be unrelated, but not sure.

For *psychModel*, only this line will need to be changed: https://github.com/jasonmoy28/psycModel/blob/a0742266dc44a3607821e5d1e67ed61690df3f9c/R/efa_summary.R#L74

**Comment by strengejacke** [comment]
Yes, cvms is unrelated. I already submitted a fix for a past update (https://github.com/LudvigOlsen/cvms/commit/c8f63728162464d25671ac06a5c66b68bb8ec0fb), but I missed that I had to change the list to a data frame, else `ignore_attr` has no effect. Whenever we change attributes from `model_parameters()`, _cvms_ will have test errors.

**Comment by strengejacke** [comment]
How can we fix this issue?

``` r
library(cvms)
library(testthat)
data(participant.scores)

xpectr::set_test_seed(1)
dat <- participant.scores
dat$.folds_1 <- factor(sample(c(1,2), size = nrow(dat), replace = TRUE))
dat$.folds_2 <- factor(sample(c(1,2,3), size = nrow(dat), replace = TRUE))
dat$.folds_3 <- factor(sample(c(1,2,3,4), size = nrow(dat), replace = TRUE))

CV <- cross_validate(
  dat,
  "score~diagnosis",
  fold_cols = paste0(".folds_", 1:3),
  family = "gaussian",
  REML = FALSE,
  verbose = FALSE
)

xpectr::set_test_seed(42)
# Testing values
if (utils::packageVersion("parameters") > "0.18.1") {
  expect_equal(
    CV$Coefficients[[1]],
    tibble::tibble(
      `Fold Column` = c(
        ".folds_1", ".folds_1", ".folds_1", ".folds_1",
        ".folds_2", ".folds_2", ".folds_2", ".folds_2",
        ".folds_2", ".folds_2", ".folds_3", ".folds_3",
        ".folds_3", ".folds_3", ".folds_3", ".folds_3",
        ".folds_3", ".folds_3"
      ),
      Fold = c(1L, 1L, 2L, 2L, 1L, 1L, 2L, 2L, 3L, 3L, 1L, 1L, 2L, 2L, 3L, 3L, 4L, 4L),
      term = c(
        "(Intercept)", "diagnosis", "(Intercept)", "diagnosis", "(Intercept)",
        "diagnosis", "(Intercept)", "diagnosis", "(Intercept)", "diagnosis",
        "(Intercept)", "diagnosis", "(Intercept)", "diagnosis", "(Intercept)",
        "diagnosis", "(Intercept)", "diagnosis"
      ),
      estimate = c(
        48.6666666666667, -14.2121212121212, 51.6666666666667, -26.952380952381,
        54.375, -24.175, 47.5714285714286, -22.1714285714286, 50.4444444444444,
        -14.3535353535354, 49.125, -19.0073529411765, 52.2222222222222,
        -29.5972222222222, 50.5, -18.9705882352941, 51.6666666666667,
        -16.0833333333333
      ),
      std.error = c(
        8.41855414379772, 9.49740995414852, 6.21405764952783, 9.39477209901097,
        6.10243657425927, 7.55651524308974, 5.15115732323402, 6.71628744224089,
        6.01599273599761, 8.1119629503789, 5.86007109036599, 7.1063800232963,
        5.42520220176549, 7.90852326457585, 5.39137655673118, 6.79449349609756,
        5.45953571418165, 7.22228688680003
      ),
      conf.level = c(
        0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95,
        0.95, 0.95, 0.95, 0.95, 0.95, 0.95
      ),
      conf.low = c(
        30.324212890912, -34.9051998688293, 38.3388385420056, -47.1021630863613,
        41.6842884135979, -39.8896337174252, 36.5919966357145, -36.4868563880417,
        37.8053127114571, -31.3961371056051, 37.0025193413177, -33.7080200588983,
        40.6586774546993, -46.4538405405513, 39.3962521290018, -32.9641095369386,
        40.2397270909832, -31.1997535152435
      ),
      conf.high = c(
        67.0091204424213, 6.48095744458683, 64.9944947913278, -6.80259881840061,
        67.0657115864021, -8.46036628257483, 58.5508605071426, -7.85600075481539,
        63.0835761774318, 2.6890663985344, 61.2474806586823, -4.30668582345469,
        63.7857669897452, -12.7406039038931, 61.6037478709982, -4.97706693364964,
        63.0936062423501, -0.966913151423173
      ),
      statistic = c(
        5.78088182785179, -1.49642073794164, 8.31448138730939, -2.86887011928883,
        8.91037528015606, -3.19922599535646, 9.23509525846942, -3.30114349067095,
        8.38505740583801, -1.76942812009082, 8.38300410395395, -2.67468850228473,
        9.62585730080767, -3.74244612199539, 9.36681002868373, -2.79205333645399,
        9.46356418778573, -2.22690313821906
      ),
      df.error = c(
        12L, 12L, 14L, 14L, 21L, 21L, 15L, 15L, 18L, 18L, 23L, 23L, 15L, 15L, 25L, 25L, 19L, 19L
      ),
      p.value = c(
        8.73044693341471e-05, 0.160375077413601, 8.71744764220858e-07, 0.0123802797806211,
        1.40309391631771e-08, 0.00431125235564896, 1.40863068775986e-07, 0.00484752749572593,
        1.2467032478442e-07, 0.0937616722887625, 1.90501051336518e-08, 0.0135331351313378,
        8.2329274043691e-08, 0.00196103615278914, 1.18033672582856e-09, 0.0098923901197315,
        1.26960822180091e-08, 0.038244411370448
      )
    ),
    tolerance = 1e-4,
    ignore_attr = TRUE
  )
}
#> Error: CV$Coefficients[[1]] not equal to tibble::tibble(...).
#> Attributes: < Names: 2 string mismatches >
#> Attributes: < Length mismatch: comparison on first 2 components >
#> Attributes: < Component 1: Modes: logical, character >
#> Attributes: < Component 1: Lengths: 1, 3 >
#> Attributes: < Component 1: target is logical, current is character >
#> Attributes: < Component 2: Numeric: lengths (1, 18) differ >
```

<sup>Created on 2022-09-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
resolved, looks like _cvms_ uses testthat edition v2, so I needed to add `check.attributes = FALSE`.

**Pull request merged**
