### PR TITLE
Fix row name for the prevalence ratio in methods_epi2x2.R

### PR DESCRIPTION
**Pull request by snhansen**
`insight::get_parameters()` returns something named "RR" and not "PR".

### CODE REVIEW

**Comment by strengejacke** [comment]
Do you have an example?

**Comment by snhansen** [comment]
> Do you have an example?

Sure. Here's one showing that the first parameter is named "RR" and not "Prevalence Ratio":

```
mtcars |> xtabs(~ am + vs, data = _) |> epiR::epi.2by2() |> parameters::parameters()
#> Parameter                               | Coefficient |              CI
#> -----------------------------------------------------------------------
#> RR                                      |        1.37 | [  0.69,  2.70]
#> Odds Ratio                              |        2.00 | [  0.48,  8.40]
#> Attributable Risk                       |       17.00 | [-17.71, 51.71]
#> Attributable Fraction in Exposed (%)    |       26.92 | [-44.28, 62.99]
#> Attributable Risk in Population         |       10.10 | [-21.99, 42.19]
#> Attributable Fraction in Population (%) |       17.95 | [-29.51, 48.01]
#> 
#> Test that Odds Ratio = 1: Chi2(1) = 0.91, p = 0.341
```

This is because `insight::get_parameters()` returns something in which the parameter is named "RR" and not "PR".
```
mtcars |> xtabs(~ am + vs, data = _) |> epiR::epi.2by2() |> insight::get_parameters()
#>   Parameter   Estimate
#> 1        RR  1.3684211
#> 2        OR  2.0000000
#> 3     ARisk 17.0040486
#> 4    AFRisk  0.2692308
#> 5    PARisk 10.0961538
#> 6   PAFRisk  0.1794872
```

**Comment by strengejacke** [comment]
Ok, but then we should simply add 

```r
pretty_names[pretty_names == "RR"] <- "Risk Ratio"
```

and keep the prevalence ratio string.

**Comment by snhansen** [comment]
Yeah, that's fine too. I just thought you intentionally wanted "Prevalence Ratio" over "Risk Ratio" but I agree that "Risk Ratio" is true to the original output. Not sure if you want me to do anything here as I'm not too familiar with this way of working. If it's easier for you to make that change, then go ahead.

**Comment by strengejacke** [comment]
Thanks for reporting this issue, should be resolved with this PR. I added a test for completeness.

**Pull request merged**
