### PR TITLE
Make CI default consistent across packages in the 'verse

### PR DESCRIPTION
**Pull request by bwiernik**
As discussed at https://github.com/easystats/bayestestR/discussions/250 and https://github.com/easystats/bayestestR/pull/403, there isn't much validity to the computational reasons to choose 90% over 95%, so let's be consistent across packages.

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
Oh boi, this is gonna unleash the wrath of the strange Jacke ^^

**Review by DominiqueMakowski — APPROVED** [review]

**Comment by bwiernik** [comment]
From the perspective of the easyverse philosophy of accessibility, I think consistency is a really important feature.

**Comment by strengejacke** [comment]
Yeah, that's probably right... I'm ok with these changes.

**Comment by DominiqueMakowski** [comment]
> Yeah, that's probably right... I'm ok with these changes.

**Comment by bwiernik** [comment]
@strengejacke The test `test-model_parameters.vgam.R` is failing on my system with this error. Could you check it out?

``` r
require("VGAM")
#> Loading required package: VGAM
#> Loading required package: stats4
#> Loading required package: splines
data("pneumo")
data("hunua")

set.seed(123)
pneumo <- transform(pneumo, let = log(exposure.time))

m1 <- suppressWarnings(vgam(
    cbind(normal, mild, severe) ~ s(let) + exposure.time,
    cumulative(parallel = TRUE),
    data = pneumo,
    trace = FALSE
))
```

<sup>Created on 2021-08-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>


Also, @DominiqueMakowski or @strengejacke do you know why *see* isn't available to GitHub Actions for some reason?

**Comment by bwiernik** [comment]
Also @strengejacke should `rope_ci` default to `1.0` or to `.95`? It was mostly `1.0` before I made changes, but one function had `.89`. I'm not exactly sure what this argument does.

**Comment by mattansb** [comment]
Should default to 0.95 (:

**Pull request merged**
