### PR TITLE
dev - Reorganization of parameters (effectsize)

### PR DESCRIPTION
**Pull request by DominiqueMakowski**
This PR will track the reorganization of parameters related to what has been decided #110 #138 

***~Do not merge this until effectsize is on CRAN~***

The goal is to transfer things related to effect sizes there.

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
The question is, what is the best order to update on CRAN? parameters -> effectsize -> see?

**Comment by DominiqueMakowski** [comment]
The ANOVA effect sizes functions are based on `.extract_parameters_anova()` , which is currently an internal. Should we export the `extract_parameters_*` functions (but document them as being mostly dev-related and that user should consider using `model_parameters` instead)?

**Comment by strengejacke** [comment]
> Do not merge this until effectsize is on CRAN

pkg effectsize needs `dof()`, so we _have_ to merge this PR _before_ effectsize is on CRAN, no? But this won't work, as it breaks reverse dependencies.

**Comment by DominiqueMakowski** [comment]
In theory yes, it should be merged after effectsize contrary to what the message said.

One of the possibilities I thought about is to submit effectsize just before parameters, with all the tests and examples that require parameters deactivated. This way, it would pass on CRAN before parameters is updated, so we can then quickly submit updated parameters and sjpacks. What do you think?

**Comment by strengejacke** [comment]
Ok, sounds good. I trust you, because I couldn't follow the development of effectsize in detail last week ;-)

**Comment by DominiqueMakowski** [comment]
> I trust you

\**starts to sweat*\* 😅 should be alright hopefully :)

Let's start by submitting insight and bayetestR

**Comment by strengejacke** [comment]
I'm still not 100% convinced that standardize and normalize should also go into effectsize, especially since effectsize can easily import or re-export those functions from parameters.

and, model_parameters() is losing its feature to show std. coefficients...

**Comment by mattansb** [comment]
> and, model_parameters() is losing its feature to show std. coefficients...

😨😨😨😨😨 I thought `parameters` was dep on `effectsize`??

Also, why are the `interpret_*` functions in `effectsize`? Shouldn't they be in `report`??

**Comment by mattansb** [comment]
> and, model_parameters() is losing its feature to show std. coefficients...

I would consider this a breaking change - it will definitely break my code :/

I know we can't have circular dependency - but can't parameters suggest `effectsize`, and have the whole `if(!require("effectsize"))` thing?

**Comment by strengejacke** [comment]
Yeah, but it's not planned for the forthcoming update of parameters and initial release of effectsize.

**Comment by strengejacke** [comment]
My feeling is that standardization is more a part of the parameters package than effectsize. _effectsize_ comprises all the anova-effect-size and effect-size-conversion stuff, which is not needed for model parameters. however, standardization can be useful for both packages, so it should live in the "more basic" package. If standardization is in parameters, it can be used by parameters _and_ effectsize. Else, it can only be used in effectsize. Don't you think so, too?

**Comment by DominiqueMakowski** [comment]
Should we remove all the ANOVA ES from here as well to avoid conflicts once effectsize will be up?

**Comment by strengejacke** [comment]
Yes, I think we can remove all effectsize stuff, even for the next update. It shouldn't conflict with any reverse dependencies.

**Comment by strengejacke** [comment]
Based on https://github.com/easystats/parameters/issues/142#issuecomment-544124870, we can merge this now, and I will then "re-implement" the standardized options based on suggesting effectsize, right?

**Comment by DominiqueMakowski** [comment]
I'd say, altough we might want to remove the ANOVA ES things before merging and try to have that travis passing just to make sure that the new version "works"

**Comment by strengejacke** [comment]
What are the "ANOVA ES" things?

**Comment by DominiqueMakowski** [comment]
ANOVA effect sizes functions that have been copied to effectsize but not removed from here

**Comment by strengejacke** [comment]
Ah, I see. Thought these have already been removed as well. Yes yes, away with them ;-)

**Comment by strengejacke** [comment]
> I'd say, altough we might want to remove the ANOVA ES

That was actually my main intentsion when I suggested the effect size package :-D

**Pull request merged**
