### PR TITLE
Add the option to calculate Q1 and Q3

### PR DESCRIPTION
**Pull request by jmgirard**
I really like describe_parameters() but have missed the ability to calculate quartiles (25th and 75th percentiles), so I thought I'd try to add this as an optional (default = FALSE) argument.

### CODE REVIEW

**Comment by jmgirard** [comment]
Looks like I needed to do stats::quantile(), sorry.

**Comment by strengejacke** [comment]
Thanks for this PR. Looks like some issues still needs to be resolved (documentation of argument?).

Don't forget to add yourself as contributor to the description file, if you like.

**Comment by jmgirard** [comment]
Ok, I'll work on it. Still new to collaborating on shared repos so please be patient with me.

**Comment by IndrajeetPatil** [comment]
I think you just need to run `roxygen2::roxygenize()`, so that the docs (`.Rd` files) are also updated to contain the new argument.

**Comment by strengejacke** [comment]
I just realized that there was a bug (in the current parameters, not due to your PR, but I realized that only by reviewing this PR).

**Comment by strengejacke** [comment]
Great, thanks! Is there anything you want to add/modify? Else, this is ready for merging.

**Comment by jmgirard** [comment]
I think we're good, thanks!

**Comment by IndrajeetPatil** [comment]
@strengejacke We need to update print method to also return `Quartiles` column in brackets, right?

Screenshot 2021-03-18 at 15 23 08

**Comment by strengejacke** [comment]
@jmgirard used the same formatting (i.e. brackets), but I changed that and removed the brackets. I think _brackets_ (or parenthesis) indicate an _interval_ (or a range), while the quartiles here indicate two cut-off points. The quartiles do not range from (e.g.) 5.10 to 6.40. Thus, I thought removing brackets would make more sense.

**Comment by IndrajeetPatil** [comment]
Oh, good point! 

Yeah, that makes sense.

**Pull request merged**
