### PR TITLE
stylistic changes

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
I will merge for now, and we can build on it further later.

**Comment by strengejacke** [comment]
But checks don't pass.

**Comment by IndrajeetPatil** [comment]
Uh-oh, let me check what happened.

**Comment by strengejacke** [comment]
Looks like an invalid argument was used in the tests, which didn't do any harm, because we didn't pass down the dots to `boot()` ;-)
When we use boostrapping, dots may only contain valid arguments for `boot()`.

**Comment by strengejacke** [comment]
@DominiqueMakowski This PR breaks a lot of other stuff, in particular all parameters that are passed down to `bayestestR::describe_posterior()`. Not sure what's the best way to go... Maybe we can capture the dots, then "filter" for valid arguments for `boot()`, and only pass those valid arguments to `boot()` (via `do.call()`).

@IndrajeetPatil would you revise this PR accordingly to not break current functionality?

**Comment by DominiqueMakowski** [comment]
> Maybe we can capture the dots, then "filter" for valid arguments

wouldn't something like `parallel <- ifelse("parallel" %in% names(as.list(...)), as.list(...)$parallel, "no")` and then pass parallel to boot work?

**Comment by IndrajeetPatil** [comment]
I prefer to then just go back to the earlier implementation I had in mind: 
explicitly providing `parallel` and `ncpus` argument, which, yes, complicates the API slightly, but would not cause any problems for any of the methods.

**Comment by IndrajeetPatil** [comment]
As discussed in #436, I've decided to revert all `boot`-related changes. Now the PR only contains stylistic 80-width changes.

**Pull request merged**
