### PR TITLE
update to v2 for pkgdown GHA

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by strengejacke** [comment]
It's not the circular dependency, parameters is suggesting a non existing effectsize version

**Comment by strengejacke** [comment]
I should reduce the version number to 0.5.0

**Comment by IndrajeetPatil** [comment]
Ah, I see. `effectsize 0.5.1` is still not merged in the `main` branch.

Yeah, let's see if that changes things.

**Comment by mattansb** [comment]
As long as the actual code and test require a higher version of effectsize, we should be good.

**Pull request merged**
