### PR TITLE
add CIs for describe_dist; style code; minor pkgdown cleanup

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
The tests are already failing on Travis, so they don't have to do anything with the changes I have made.

This just adds symmetric confidence intervals for the centrality parameter-

```r
parameters::describe_distribution(rnorm(100))
#>  Mean |   SD |   SE |         Range | Skewness | Kurtosis | CI_low | CI_high |   n | n_Missing
#> ----------------------------------------------------------------------------------------------
#> -0.04 | 1.06 | 0.11 | [-3.46, 2.38] |    -0.41 |     0.75 |  -0.21 |    0.21 | 100 |         0
```

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Sigh. The CIs being computed here are incorrect. 

I am amazed by how incompetent I am at R if I you take away `tidyverse` from me. 

Can you please merge this as it is (if the other changes look okay) and then fix the CIs afterwards?

**Comment by mattansb** [comment]
Sorry, what CI is this? Of the mean?

**Comment by mattansb** [comment]
If so, using the median as central eat should force a different ci computation - also a different SE computation... (No straightforward way to do this other than bootstrap...)

**Comment by IndrajeetPatil** [comment]
Yepp, confidence intervals for the centrality parameter estimate.

**Comment by mattansb** [comment]
If so, using the median as central eat should force a different ci computation - also a different SE computation... (No straightforward way to do this other than bootstrap...)

**Comment by strengejacke** [comment]
> I am amazed by how incompetent I am at R if I you take away `tidyverse` from me.

image

**Pull request closed without merging**
