### PR TITLE
implement p_calibration()

### PR DESCRIPTION
**Pull request by strengejacke**

### CODE REVIEW

**Comment by strengejacke** [comment]
- [ ] add tests

**Comment by strengejacke** [comment]
``` r
library(parameters)
model <- lm(mpg ~ wt + as.factor(gear) + am, data = mtcars)
p_calibration(model)
#> Warning: Some p-values were larger than the calibration cut-off.
#>   Returning `NA` for p-values that cannot be calibrated.
#> Parameter        |      p | p (calibrated)
#> ------------------------------------------
#> (Intercept)      | < .001 |         < .001
#> wt               | < .001 |         < .001
#> as.factor(gear)4 | 0.242  |         0.483 
#> as.factor(gear)5 | 0.660  |               
#> am               | 0.925  |               
#> Calibrated p-values indicate the posterior probability of H0.
```

<sup>Created on 2022-11-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mattansb** [comment]
WhatTheHeckExcuseMeWhatGIF

**Comment by strengejacke** [comment]
I think it's roughly comparable with `bayestestR::p_to_bf()`.

**Pull request merged**
