### PR TITLE
support wide anova tables

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
Example:

``` r
library(parameters)

model <- aov(Sepal.Width ~ Species, data = iris)

set.seed(123)

# default
model_parameters(
  model,
  omega_squared = "partial",
  ci = .9,
  verbose = FALSE
)
#> Parameter | Sum_Squares |  df | Mean_Square |     F |      p | Omega2 | Omega2 90% CI
#> -------------------------------------------------------------------------------------
#> Species   |       11.34 |   2 |        5.67 | 49.16 | < .001 |   0.39 |  [0.29, 0.48]
#> Residuals |       16.96 | 147 |        0.12 |       |        |        |              
#> 
#> Anova Table (Type 1 tests)

# wide table
model_parameters(
  model,
  omega_squared = "partial",
  ci = .9,
  table_wide = TRUE,
  verbose = FALSE
)
#> Parameter | Sum_Squares | df | Mean_Square |     F |      p | Omega2 | Omega2 90% CI | Sum_Squares_Error
#> --------------------------------------------------------------------------------------------------------
#> Species   |       11.34 |  2 |        5.67 | 49.16 | < .001 |   0.39 |  [0.29, 0.48] |             16.96
#> 
#> Anova Table (Type 1 tests)
```

<sup>Created on 2021-06-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

### CODE REVIEW

**Comment by bwiernik** [comment]
Shouldn't there be a df_error column here?

**Comment by IndrajeetPatil** [comment]
Yikes! Yes, it's missing. Will look into it now.

**Comment by IndrajeetPatil** [comment]
Also, `Mean_Square_Error` is missing.

**Comment by IndrajeetPatil** [comment]
https://github.com/easystats/parameters/pull/513 fixes it.

**Pull request merged**
