### PR TITLE
marginaleffects_0_18_0

### PR DESCRIPTION
**Pull request by vincentarelbundock**
Version 0.18.0 of `marginaleffects` introduces some deprecations and other minor breaking changes in preparation for the stabilization of the user "final" user interface in `marginaleffects` 1.0.0.

This PR adjusts some tests to account for this. The changes are relatively minor.

### CODE REVIEW

**Comment by strengejacke** [comment]
Thanks Vincent!
I guess the latest _marginaleffects_ update broke _parameters_ (see https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/parameters-00check.html) - does this PR resolve those issues?

**Comment by strengejacke** [comment]
Sorry, results seem to be here:
https://win-builder.r-project.org/incoming_pretest/ggeffects_1.4.0_20240205_151436/reverseDependencies/summary.txt

**Comment by vincentarelbundock** [comment]
Yep yep. Sorry for the breakage, but I expect this PR to resolve all marginaleffects-related issues raised on CRAN.

Important usage note: `tidy()` no longer averages estimates by default, so users need to call the `avg_` function explicitly (or use the `by` argument).

**Comment by strengejacke** [comment]
I just checked, issues should be resolved. Please don't merge this PR, I will use this directly for submitting an update to CRAN.

**Comment by vincentarelbundock** [comment]
Thanks a lot!

**Comment by strengejacke** [comment]
on CRAN

**Pull request merged**
