### PR TITLE
use get_varcov directly for robust VCOV

### PR DESCRIPTION
**Pull request by strengejacke**
@vincentarelbundock Not sure, but I think it's really that easy to switch to `get_varcov()` for robust estimation, right?

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
Yep, that was my big master plan :)

Crossing fingers...

**Comment by vincentarelbundock** [comment]
You also need to require the very latest version of `insight`

**Comment by strengejacke** [comment]
Yes, I think the insight-GH should already be used via "Remotes" in the DESCRIPTION file.

**Comment by strengejacke** [comment]
passed the wrong argument names, that's why tests were failing... What was the reason why we used `do.call()` here? I now call `insight::get:varcov()` directly.

**Comment by vincentarelbundock** [comment]
Commit https://github.com/easystats/insight/commit/bbdb4808567806a942ea3e59d47f8f2dc490d044 from `insight` removes a lot of the warnings on previous testing runs.

Unfortunately, I probably won't have time to look more at this in the very short run.

**Comment by bwiernik** [comment]
This looks good to me.

**Comment by vincentarelbundock** [comment]
same. looks simple enough, and the tests now look like they are passing.

**Comment by strengejacke** [comment]
merge now, or after _insight_ was updated on CRAN again?

**Pull request merged**
