### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by strengejacke** [comment]
Why have you removed `stats::` from predict?

**Comment by DominiqueMakowski** [comment]
Because predict.kmeans doesn't exist, hence I added this method in parameters

**Comment by strengejacke** [comment]
yes, but `predict.kmeans()` is an S3-method, and it's called via `stats::predict()` on kmeans-objects?

**Comment by DominiqueMakowski** [comment]
True

**Pull request merged**
