### PR TITLE
parameters.marginaleffects - preserve attributes from original input

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
Doesn't work:

``` r
  model <- lm(Sepal.Width ~ Species * Petal.Length, data = iris)
  
  means <- marginaleffects::predictions(model, newdata=insight::get_data(model), by="Species")
  attr(means, "SOMETHING") <- "Yes"
  attributes(parameters::parameters(means))$SOMETHING 
#> NULL
```

<sup>Created on 2024-02-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DominiqueMakowski** [comment]
and I can't seem to trace where it gets overwritten again 🤔

**Comment by vincentarelbundock** [comment]
As far as I can tell, `parameters` never preserves the attributes of the model object. Try 

```r
mod <- lm(mpg ~ wt * factor(cyl), data = dat)
attr(mod, "SOMETHING") <- "yes"
attributes(parameters::parameters(mod))$SOMETHING 
```

**Comment by DominiqueMakowski** [comment]
Mmh fair. I don't *need* this, it was mostly for convenience reasons in modelbased but I can do without

**Pull request closed without merging**
