### PR TITLE
BayesFactor initial support and priors info for rstanarm

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
@strengejacke I realised that your proposal to replace the dplyr::do didn't actually work as expected... 😅 (the output wasn't standardized). Also, I think it would be good to preserve the  grouped_df class so that there is no unintended ungrouping.

Re-added the dplyr placeholder for now

**Comment by strengejacke** [comment]
Do you have an example where it did not work? I have checked this with mtcars, and standardizing worked as expedted... Maybe I have missed something?

**Comment by DominiqueMakowski** [comment]
```r
standardize_nondplyr <- function(x, robust = FALSE, select = NULL, exclude = NULL, ...) {
  grps <- attr(x, "groups", exact = TRUE)
  x <- as.data.frame(x)
  for (i in grps[[".rows"]]) {
    x[i, ] <- standardize(
      x[i, ],
      select = select,
      exclude = exclude,
      robust = robust,
      ...
    )
  }
  x
}


standardize_dplyr <- function(x, robust = FALSE, select = NULL, exclude = NULL, ...) {
  x <- dplyr::do_(x, "standardize(., select = select, exclude = exclude, robust = robust, ...)")
  return(x)
}





library(parameters)
library(dplyr)

iris %>%
  group_by(Species) %>%
  standardize_nondplyr() %>%
  summary()

iris %>%
  group_by(Species) %>%
  standardize_dplyr() %>%
  summary()
  
```

**Comment by strengejacke** [comment]
Hm, results are identical for me:

``` r
standardize_nondplyr <- function(x, robust = FALSE, select = NULL, exclude = NULL, ...) {
  grps <- attr(x, "groups", exact = TRUE)
  x <- as.data.frame(x)
  for (i in grps[[".rows"]]) {
    x[i, ] <- standardize(
      x[i, ],
      select = select,
      exclude = exclude,
      robust = robust,
      ...
    )
  }
  x
}

standardize_dplyr <- function(x, robust = FALSE, select = NULL, exclude = NULL, ...) {
  x <- dplyr::do_(x, "standardize(., select = select, exclude = exclude, robust = robust, ...)")
  return(x)
}

library(parameters)
library(dplyr)

iris %>%
  group_by(Species) %>%
  standardize_nondplyr() %>%
  summary()
#>   Sepal.Length       Sepal.Width        Petal.Length     
#>  Min.   :-2.65459   Min.   :-2.97575   Min.   :-2.68136  
#>  1st Qu.:-0.64075   1st Qu.:-0.60148   1st Qu.:-0.73403  
#>  Median :-0.01702   Median : 0.08062   Median : 0.08697  
#>  Mean   : 0.00000   Mean   : 0.00000   Mean   : 0.00000  
#>  3rd Qu.: 0.55037   3rd Qu.: 0.70078   3rd Qu.: 0.70029  
#>  Max.   : 2.25255   Max.   : 2.56421   Max.   : 2.52211  
#>   Petal.Width            Species  
#>  Min.   :-2.2793   setosa    :50  
#>  1st Qu.:-0.4588   versicolor:50  
#>  Median :-0.1315   virginica :50  
#>  Mean   : 0.0000                  
#>  3rd Qu.: 0.8183                  
#>  Max.   : 3.3591

iris %>%
  group_by(Species) %>%
  standardize_dplyr() %>%
  summary()
#> Warning: do_() is deprecated. 
#> Please use group_map() instead
#> This warning is displayed once per session.
#>   Sepal.Length       Sepal.Width        Petal.Length     
#>  Min.   :-2.65459   Min.   :-2.97575   Min.   :-2.68136  
#>  1st Qu.:-0.64075   1st Qu.:-0.60148   1st Qu.:-0.73403  
#>  Median :-0.01702   Median : 0.08062   Median : 0.08697  
#>  Mean   : 0.00000   Mean   : 0.00000   Mean   : 0.00000  
#>  3rd Qu.: 0.55037   3rd Qu.: 0.70078   3rd Qu.: 0.70029  
#>  Max.   : 2.25255   Max.   : 2.56421   Max.   : 2.52211  
#>   Petal.Width            Species  
#>  Min.   :-2.2793   setosa    :50  
#>  1st Qu.:-0.4588   versicolor:50  
#>  Median :-0.1315   virginica :50  
#>  Mean   : 0.0000                  
#>  3rd Qu.: 0.8183                  
#>  Max.   : 3.3591
```

**Comment by DominiqueMakowski** [comment]
```r
> iris %>%
+   group_by(Species) %>%
+   standardize_nondplyr() %>%
+   summary()
  Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   
 Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  
 1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  
 Median :5.800   Median :3.000   Median :4.350   Median :1.300  
 Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  
 3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  
 Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  
       Species  
 setosa    :50  
 versicolor:50  
 virginica :50  
                
                
                
> iris %>%
+   group_by(Species) %>%
+   standardize_dplyr() %>%
+   summary()
  Sepal.Length       Sepal.Width      
 Min.   :-2.65459   Min.   :-2.97575  
 1st Qu.:-0.64075   1st Qu.:-0.60148  
 Median :-0.01702   Median : 0.08062  
 Mean   : 0.00000   Mean   : 0.00000  
 3rd Qu.: 0.55037   3rd Qu.: 0.70078  
 Max.   : 2.25255   Max.   : 2.56421  
  Petal.Length       Petal.Width     
 Min.   :-2.68136   Min.   :-2.2793  
 1st Qu.:-0.73403   1st Qu.:-0.4588  
 Median : 0.08697   Median :-0.1315  
 Mean   : 0.00000   Mean   : 0.0000  
 3rd Qu.: 0.70029   3rd Qu.: 0.8183  
 Max.   : 2.52211   Max.   : 3.3591  
       Species  
 setosa    :50  
 versicolor:50  
 virginica :50  
```

Well this is weird

**Comment by DominiqueMakowski** [comment]
```r
x <- iris %>%
  group_by(Species)

attr(x, "groups", exact = TRUE)
# NULL
```

The first line of the function returns a NULL for me

**Comment by strengejacke** [comment]
Ok, so this might be a dplyr-issue... I have dplyr 0.8 installed. Could you post `str(group_by(iris, Species))`?

**Comment by DominiqueMakowski** [comment]
```
> str(group_by(iris, Species))
Classes ‘grouped_df’, ‘tbl_df’, ‘tbl’ and 'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...
 - attr(*, "vars")= chr "Species"
 - attr(*, "drop")= logi TRUE
 - attr(*, "indices")=List of 3
  ..$ : int  0 1 2 3 4 5 6 7 8 9 ...
  ..$ : int  50 51 52 53 54 55 56 57 58 59 ...
  ..$ : int  100 101 102 103 104 105 106 107 108 109 ...
 - attr(*, "group_sizes")= int  50 50 50
 - attr(*, "biggest_group_size")= int 50
 - attr(*, "labels")='data.frame':	3 obs. of  1 variable:
  ..$ Species: Factor w/ 3 levels "setosa","versicolor",..: 1 2 3
  ..- attr(*, "vars")= chr "Species"
  ..- attr(*, "drop")= logi TRUE
> 
```

Hum could be... should I upgrade to the latest?

**Comment by strengejacke** [comment]
I'll revise the function so it works both for dplyr >= 0.8 and below.

**Comment by DominiqueMakowski** [comment]
@strengejacke It works... almost ^^ 

For some bizarre reasons, the standardization in the grouped case is not total... I wonder if it could be a difference in the mean and SD used for the computation. I will try to look more into it today.

## Current non-dplyr
```r
library(report)
library(parameters)
library(dplyr)

iris %>%
  group_by(Species) %>%
  standardize() %>%
  report()
```

```
The data contains 150 observations, grouped by Species, of the following variables:
- setosa (n = 50):
  - Sepal.Length: Mean = -0.03 +- 1.02 [-1.98, 2.23]
  - Sepal.Width: Mean = 0.03 +- 1.02 [-2.96, 2.53]
  - Petal.Length: Mean = -0.09 +- 1.18 [-4.53, 2.49]
  - Petal.Width: Mean = -0.09 +- 1.17 [-4.35, 3.32]
- versicolor (n = 50):
  - Sepal.Length: Mean = 0.01 +- 0.99 [-1.92, 2.03]
  - Sepal.Width: Mean = -0.04 +- 0.98 [-2.42, 1.92]
  - Petal.Length: Mean = 0.04 +- 0.84 [-2.44, 1.44]
  - Petal.Width: Mean = 0.04 +- 0.86 [-2.46, 1.95]
- virginica (n = 50):
  - Sepal.Length: Mean = 0.15 +- 1.28 [-2.63, 5.90]
  - Sepal.Width: Mean = 0.07 +- 1.08 [-2.38, 3.00]
  - Petal.Length: Mean = 0.15 +- 1.18 [-1.76, 5.10]
  - Petal.Width: Mean = 0.09 +- 0.97 [-2.11, 1.80]
```

## dplyr
```r
standardize_dplyr <- function(x, robust = FALSE, select = NULL, exclude = NULL, ...) {
  x <- dplyr::do_(x, "standardize(., select = select, exclude = exclude, robust = robust, ...)")
  return(x)
}

 
iris %>%
  group_by(Species) %>%
  standardize_dplyr() %>%
  report()
```
```
The data contains 150 observations, grouped by Species, of the following variables:
- setosa (n = 50):
  - Sepal.Length: Mean = -0.00 +- 1.00 [-2.00, 2.25]
  - Sepal.Width: Mean = 0.00 +- 1.00 [-2.98, 2.56]
  - Petal.Length: Mean = 0.00 +- 1.00 [-2.66, 2.52]
  - Petal.Width: Mean = 0.00 +- 1.00 [-1.39, 3.36]
- versicolor (n = 50):
  - Sepal.Length: Mean = 0.00 +- 1.00 [-2.01, 2.06]
  - Sepal.Width: Mean = -0.00 +- 1.00 [-2.45, 2.01]
  - Petal.Length: Mean = 0.00 +- 1.00 [-2.68, 1.79]
  - Petal.Width: Mean = -0.00 +- 1.00 [-1.65, 2.40]
- virginica (n = 50):
  - Sepal.Length: Mean = -0.00 +- 1.00 [-2.65, 2.06]
  - Sepal.Width: Mean = -0.00 +- 1.00 [-2.40, 2.56]
  - Petal.Length: Mean = 0.00 +- 1.00 [-1.91, 2.44]
  - Petal.Width: Mean = 0.00 +- 1.00 [-2.28, 1.73]
```

**Comment by DominiqueMakowski** [comment]
I ***think*** it didn't work because, in my version, the indexing in groups was 0-based. It fixed it to add 1 to all indexes... 🤔

**Comment by strengejacke** [comment]
Yes, I think that could be the reason. Did not look exactly at the index values

**Comment by DominiqueMakowski** [comment]
Let's merge this for now as it seems to *work*, knowing that the `TEMP_get_priors.R` file should probably have to be moved to insight.

**Pull request merged**
