### PR TITLE
dev

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
https://cran.r-project.org/submit.html

Unfortunately, it got blocked until the 18th -_- -_- -_- -_-

**Comment by strengejacke** [comment]
> Unfortunately, it got blocked until the 18th

Why that? Too many tries? Haven't you done your homework before submission? ;-)

**Comment by strengejacke** [comment]
If I understood right, one request was to add people to the authors from which we have taken sourcecode, no?

**Comment by DominiqueMakowski** [comment]
> one request was to add people to the authors from which we have taken sourcecode, no?

Yes, although I think we can try explaining that these people are mentioned to credit them and for traceability purposes (we could simply imply import the packages as dependencies but in order to keep the latter to a minimum, we simply included and re-adapted some specific function) but we're not really comfortable including people as authors without asking them and without their explicit contribution to that package

**Pull request merged**
