### PR TITLE
adds support for WRS2 objects; closes #367

### LINKED ISSUE #367: feature request: adding methods for `WRS2` objects
I will add these. 

Example of `WRS2` object:

``` r
set.seed(123)
library(WRS2)
t1way(libido ~ dose, data = viagra)
#> Call:
#> t1way(formula = libido ~ dose, data = viagra)
#> 
#> Test statistic: F = 3 
#> Degrees of freedom 1: 2 
#> Degrees of freedom 2: 4 
#> p-value: 0.16 
#> 
#> Explanatory measure of effect size: 0.79 
#> Bootstrap CI: [0.42; 1.33]
```

<sup>Created on 2020-12-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
- [x] method for `t1way` objects
- [x] method for `yuen` objects 
- [x] methods for `mcp1` and `mcp2` objects

### CODE REVIEW

**Comment by strengejacke** [comment]
To have some nicer printing options, you may think adding some attributes, similar to `htest` objects:

https://github.com/easystats/parameters/blob/d29ea171e6e335677742f858a31657cd0deb5ae0/R/methods_htest.R#L497-L523

**Comment by IndrajeetPatil** [comment]
I will just use the `htest` function here since the output is pretty similar. 

Btw, the failing test (at `test-model_parameters.htest.R:30:5`) has nothing to do with changes I made, right?

**Comment by strengejacke** [comment]
> Btw, the failing test (at `test-model_parameters.htest.R:30:5`) has nothing to do with changes I made, right?

No, and should be fixed already in the master branch.

**Comment by strengejacke** [comment]
can you commit this into `main`?

**Comment by IndrajeetPatil** [comment]
Yepp, will do that in a minute! Just need to finish something before pushing the changes.

**Review by strengejacke — APPROVED** [review]

**Pull request merged**
