### PR TITLE
add NA row in predict output where original data is missing

### PR DESCRIPTION
**Pull request by Tam-Pham**
#350 (need to update once this issue is resolved)

### CODE REVIEW

**Review by DominiqueMakowski — APPROVED** [review]
We tested it - just need eventually to change the names as we query the original data from the attributes

**Comment by strengejacke** [comment]
> We tested it - just need eventually to change the names as we query the original data from the attributes

Why do the vignettes fail to build?

**Comment by strengejacke** [comment]
I'm not sure if the code is correct. I just added the example from the vignette to the tests, and it errors:

```r
  data(bfi)
  d <- na.omit(bfi[, 1:25])
  model <- psych::fa(data, nfactors = 5)
  mp <- model_parameters(model, sort = TRUE, threshold = "max")

  test_that("predict model_parameters fa", {
    out <- head(predict(mp, names = c("Neuroticism", "Conscientiousness", "Extraversion", "Agreeableness", "Opennness")), 5)
    expect_equal(
      out$Neuroticism,
      c(-0.22242, 0.1618, 0.61907, -0.11692, -0.17372),
      tolerance = 0.01
    )
    expect_equal(
      out$Opennness,
      c(-1.6092, -0.17222, 0.23341, -1.06152, -0.66086),
      tolerance = 0.01
    )
  })
```

The resulting error:

> -- Error (Line 58): predict model_parameters fa ---------------------------------------------
> Error: incorrect number of dimensions
> Backtrace:
>  1. utils::head(...)
>  3. parameters:::predict.parameters_efa(...)
>  4. base::unique(which(is.na(original_data), arr.ind = TRUE)[, 1]) R/utils_pca_efa.R:83:2

**Review by strengejacke — CHANGES_REQUESTED** [review]
I'm not sure if the code is correct. I just added the example from the vignette to the tests, and it errors with this PR:

```r
  data(bfi)
  d <- na.omit(bfi[, 1:25])
  model <- psych::fa(d, nfactors = 5)
  mp <- model_parameters(model, sort = TRUE, threshold = "max")

  test_that("predict model_parameters fa", {
    out <- head(predict(mp, names = c("Neuroticism", "Conscientiousness", "Extraversion", "Agreeableness", "Opennness")), 5)
    expect_equal(
      out$Neuroticism,
      c(-0.22242, 0.1618, 0.61907, -0.11692, -0.17372),
      tolerance = 0.01
    )
    expect_equal(
      out$Opennness,
      c(-1.6092, -0.17222, 0.23341, -1.06152, -0.66086),
      tolerance = 0.01
    )
  })
```

The resulting error:

> -- Error (Line 58): predict model_parameters fa ---------------------------------------------
> Error: incorrect number of dimensions
> Backtrace:
>  1. utils::head(...)
>  3. parameters:::predict.parameters_efa(...)
>  4. base::unique(which(is.na(original_data), arr.ind = TRUE)[, 1]) R/utils_pca_efa.R:83:2

**Comment by strengejacke** [comment]
Also, I'm not quite sure why you consider this PR as necessary, since `predict()` preserves missing values and can be directly column-bound to the original data:

``` r
library(psych)
library(parameters)
data(bfi)
d <- bfi[, 1:25]
model <- psych::fa(d, nfactors = 5)
#> Loading required namespace: GPArotation
mp <- model_parameters(model, sort = TRUE, threshold = "max")
p <- predict(mp, names = c("Neuroticism", "Conscientiousness", "Extraversion", "Agreeableness", "Opennness"))

nrow(d)
#> [1] 2800
nrow(p)
#> [1] 2800

sum(!complete.cases(d))
#> [1] 364
sapply(p, function(i) sum(is.na(i)))
#>       Neuroticism Conscientiousness      Extraversion     Agreeableness 
#>               364               364               364               364 
#>         Opennness 
#>               364



data(bfi)
d <- na.omit(bfi[, 1:25])
model <- psych::fa(d, nfactors = 5)
mp <- model_parameters(model, sort = TRUE, threshold = "max")
p <- predict(mp, names = c("Neuroticism", "Conscientiousness", "Extraversion", "Agreeableness", "Opennness"))

nrow(d)
#> [1] 2436
nrow(p)
#> [1] 2436

sum(!complete.cases(d))
#> [1] 0
sapply(p, function(i) sum(is.na(i)))
#>       Neuroticism Conscientiousness      Extraversion     Agreeableness 
#>                 0                 0                 0                 0 
#>         Opennness 
#>                 0
```

<sup>Created on 2020-11-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
We're looking into it.. indeed you're right we cannot reproduce the error that we had (and wanted to fix ^^)

**Comment by Tam-Pham** [comment]
Hi all, 

Sorry for the late reply. Previously, we ran into the problem with the following code:
```
pca_measure <- principal_components(df_measure, n = 1, rotation = "promax", threshold = "max", sort = TRUE)

predict(pca_measure)
```
The output of `predict()` did not account for the NAs and so we initially thought `predict()` does not preserve missing values. Thanks for pointing out that it's not the case. We figured NAs were actually removed from `principal_components()`. 

I removed the na.omit() from principal_components() as well as the code chunk I added in previously here  219a30932a86e0d38d04cb2ebb4768b7f68bc6cc

Hope it doesn't break anything 🤞

**Comment by Tam-Pham** [comment]
oh no, `stats::prcomp()` does not tolerate NAs in data. I have reverted my previous commit. 
```
 Error in svd(x, nu = 0, nv = k) : infinite or missing values in 'x' 
6.
stop("infinite or missing values in 'x'") 
5.
svd(x, nu = 0, nv = k) 
4.
prcomp.default(x, retx = TRUE, center = TRUE, scale. = standardize, 
    ...) 
3.
stats::prcomp(x, retx = TRUE, center = TRUE, scale. = standardize, 
    ...) at principal_components.R#116
2.
principal_components.data.frame(df_measure, n = 1, rotation = "promax", 
    threshold = "max", sort = TRUE) at principal_components.R#95
1.
principal_components(df_measure, n = 1, rotation = "promax", 
    threshold = "max", sort = TRUE) 
```

**Comment by DominiqueMakowski** [comment]
Yeah so basically in `principal_component` we use prcomp which doens't allow Nans, so we na.omit the data, so later the predict function returns the components without these. @strengejacke couldn't we use `pca()`?

**Comment by strengejacke** [comment]
> @strengejacke couldn't we use `pca()`?

I don't think so.

``` r
library(psych)
data(bfi)
d <- bfi[, 1:25]
psych::pca(d, 5, use = "all.obs")
#> Error in cor(r, use = use): missing observations in cov/cor
```

<sup>Created on 2020-12-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I'm not sure why you want to preserve missings anyway? Which information would you like to get?

**Comment by strengejacke** [comment]
Ah, ok, got it... for `predict()`...

**Comment by strengejacke** [comment]
``` r
library(parameters)
library(psych)
data(bfi)
d <- bfi[, 1:25]
m <- principal_components(d, n = 5, rotation = "varimax")

p <- predict(m)
head(p, 10)
#>           RC2         RC1           RC3         RC5        RC4
#> 1  -0.5102948  0.03107115 -1.4649651106 -0.53233561 -1.7972153
#> 2   0.1367507  0.73906498 -0.6608130210 -0.42005463 -0.3811502
#> 3   0.5741947  0.55958357  0.0095754301 -1.18920221  0.1950708
#> 4  -0.2479756  0.26075390 -1.0374701850 -0.27832394 -1.4698580
#> 5  -0.3130709  0.57039709 -0.0006570845 -0.93851878 -1.0351075
#> 6   0.4061740  1.29075808  1.5913966589 -0.47118663  0.1943922
#> 7  -1.3334227 -0.18685322 -0.1304746251  0.06392848  1.1182570
#> 8   0.2362634 -1.49566196 -0.7545159733 -1.75147669 -0.4159660
#> 9   0.8994687  0.67905290  1.3938498670  0.22706624  0.1668927
#> 10 -0.1280768  0.41284710 -0.1533894634 -0.20410585 -0.3707249

p <- predict(m, keep_na = TRUE)
head(p, 10)
#>           RC2         RC1           RC3         RC5        RC4
#> 1  -0.5102948  0.03107115 -1.4649651106 -0.53233561 -1.7972153
#> 2   0.1367507  0.73906498 -0.6608130210 -0.42005463 -0.3811502
#> 3   0.5741947  0.55958357  0.0095754301 -1.18920221  0.1950708
#> 4  -0.2479756  0.26075390 -1.0374701850 -0.27832394 -1.4698580
#> 5  -0.3130709  0.57039709 -0.0006570845 -0.93851878 -1.0351075
#> 6   0.4061740  1.29075808  1.5913966589 -0.47118663  0.1943922
#> 7  -1.3334227 -0.18685322 -0.1304746251  0.06392848  1.1182570
#> 8   0.2362634 -1.49566196 -0.7545159733 -1.75147669 -0.4159660
#> 9          NA          NA            NA          NA         NA
#> 10  0.8994687  0.67905290  1.3938498670  0.22706624  0.1668927
```

<sup>Created on 2020-12-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
awesome, yeah we just arrived to the conclusion that we should adjust the functions pretty much as you did. I feel like keep_na should default to true though, as the predicting function returning a data of the same length as the original would be kind of the expected output.. don't you think?

**Comment by strengejacke** [comment]
Yes, makes sense.

**Pull request closed without merging**
