### PR TITLE
prepare CRAN hotfix

### PR DESCRIPTION
**Pull request by strengejacke**

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
When is the deadline for this update?

**Comment by strengejacke** [comment]
26th April

**Comment by strengejacke** [comment]
I was waiting to see if anything happens to cplm (https://cran.r-project.org/package=cplm), to get rid of the notes, or to remove cplm-support if it's archived, but maybe the maintainers got some more time? Will submit today or tomorrow.

**Comment by strengejacke** [comment]
cplm issues seem to be fixed: https://cran.r-project.org/web/packages/cplm/index.html

**Comment by IndrajeetPatil** [comment]
Why are we reverting the removal of re-exports?

**Comment by strengejacke** [comment]
revdep issues that can't be fixed in time

**Comment by strengejacke** [comment]
Running revdep checks now and then resubmit, if all is ok

**Comment by IndrajeetPatil** [comment]
Sure, but I was asking which packages are adversely affected by this
change. Because I thought I had taken care of this.

**Comment by strengejacke** [comment]
broom.helpers was affected, not sure if some more packages.

**Comment by strengejacke** [comment]
on CRAN

**Pull request merged**
