### PR TITLE
glmmTMB confidence intervals realigned

### PR DESCRIPTION
**Pull request by d-morrison**
See issue #639; I have attempted to correct the issue.

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Thanks.

@strengejacke can review this, but I already had a couple of comments:

- In `{easystats}`, we try to keep the hard dependencies to 0. So you will need to refactor your code to remove dependence on `{dplyr}`. 
- The base pipe (`|>`) was introduced in `R 4.0`, but we support R versions `3.4` onwards, so you also can't use it in your code.

**Comment by d-morrison** [comment]
> Thanks.
> 
> @strengejacke can review this, but I already had a couple of comments:
> 
> * In `{easystats}`, we try to keep the hard dependencies to 0. So you will need to refactor your code to remove dependence on `{dplyr}`.
> * The base pipe (`|>`) was introduced in `R 4.0`, but we support R versions `3.4` onwards, so you also can't use it in your code.

I think I switched all the edits to base R syntax; hope that helps!

**Comment by strengejacke** [comment]
Thanks for the PR! I'll take a closer look today or the next days.

**Comment by strengejacke** [comment]
Thanks, this looks good! Will wait for the checks, I think some tests might be adopted because they might contain the wrong output from `print()`.

**Pull request merged**
