### PR TITLE
std random effects

### PR DESCRIPTION
**Pull request by mattansb**
@strengejacke Started working on this - please advise!

- [x] Fixed docs
- [x] Fixed warning
- [x] Why are the random effects from the original model?

``` r
m <- lme4::lmer(Reaction ~ Days + (1 + Days | Subject),
                data = lme4::sleepstudy)
parameters::model_parameters(m, standardize = "refit")
#> # Fixed Effects
#> 
#> Parameter   | Coefficient |   SE |        95% CI |   t(174) |      p
#> --------------------------------------------------------------------
#> (Intercept) |    1.41e-15 | 0.16 | [-0.32, 0.32] | 8.76e-15 | > .999
#> Days        |        0.54 | 0.08 | [ 0.38, 0.69] |     6.77 | < .001
#> 
#> # Random Effects
#> 
#> Parameter               | Coefficient
#> -------------------------------------
#> SD (Intercept: Subject) |       24.74
#> SD (Days: Subject)      |        5.92
#> Cor (Intercept~Subject) |        0.07
#> SD (Residual)           |       25.59
#> 
#> Using residual degrees of freedom for CI/p-values.

effectsize::standardize(m) |>
  parameters::model_parameters()  
#> # Fixed Effects
#> 
#> Parameter   | Coefficient |   SE |        95% CI |   t(174) |      p
#> --------------------------------------------------------------------
#> (Intercept) |    1.41e-15 | 0.16 | [-0.32, 0.32] | 8.76e-15 | > .999
#> Days        |        0.54 | 0.08 | [ 0.38, 0.69] |     6.77 | < .001
#> 
#> # Random Effects
#> 
#> Parameter               | Coefficient
#> -------------------------------------
#> SD (Intercept: Subject) |        0.67
#> SD (Days: Subject)      |        0.30
#> Cor (Intercept~Subject) |        0.75
#> SD (Residual)           |        0.45
#> 
#> Using residual degrees of freedom for CI/p-values.
```

<sup>Created on 2021-09-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### CODE REVIEW

**Comment by mattansb** [comment]
Got it!

``` r
m <- lme4::lmer(Reaction ~ Days + (1 + Days | Subject),
                data = lme4::sleepstudy)

parameters::model_parameters(m, standardize = "refit")
#> # Fixed Effects
#> 
#> Parameter   | Coefficient |   SE |        95% CI |   t(174) |      p
#> --------------------------------------------------------------------
#> (Intercept) |    1.41e-15 | 0.16 | [-0.32, 0.32] | 8.76e-15 | > .999
#> Days        |        0.54 | 0.08 | [ 0.38, 0.69] |     6.77 | < .001
#> 
#> # Random Effects
#> 
#> Parameter               | Coefficient
#> -------------------------------------
#> SD (Intercept: Subject) |        0.67
#> SD (Days: Subject)      |        0.30
#> Cor (Intercept~Subject) |        0.75
#> SD (Residual)           |        0.45
#> 
#> Using residual degrees of freedom for CI/p-values.


effectsize::standardize(m) |>
  parameters::model_parameters()  
#> # Fixed Effects
#> 
#> Parameter   | Coefficient |   SE |        95% CI |   t(174) |      p
#> --------------------------------------------------------------------
#> (Intercept) |    1.41e-15 | 0.16 | [-0.32, 0.32] | 8.76e-15 | > .999
#> Days        |        0.54 | 0.08 | [ 0.38, 0.69] |     6.77 | < .001
#> 
#> # Random Effects
#> 
#> Parameter               | Coefficient
#> -------------------------------------
#> SD (Intercept: Subject) |        0.67
#> SD (Days: Subject)      |        0.30
#> Cor (Intercept~Subject) |        0.75
#> SD (Residual)           |        0.45
#> 
#> Using residual degrees of freedom for CI/p-values.
```

<sup>Created on 2021-09-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mattansb** [comment]
@strengejacke If this looks okay to you, I will add/fix the relevant tests (:

**Comment by bwiernik** [comment]
What was the issue?

**Comment by mattansb** [comment]
`standardize = "refit"` only showed fixed effects
https://github.com/easystats/parameters/issues/598#issue-1000591578

**Comment by mattansb** [comment]
@strengejacke Fixed and added tests.

I think you can merge this now (:

**Comment by strengejacke** [comment]
Great, thanks!

**Pull request merged**
