### PR TITLE
#166 add bootstrap SE

### PR DESCRIPTION
**Pull request by strengejacke**
commented out for now

### CODE REVIEW

**Comment by strengejacke** [comment]
❓ ❔

**Comment by mattansb** [comment]
@strengejacke 
??

**Comment by strengejacke** [comment]
You added several lines of commented code, so actually you changed nothing regarding functionality...

**Comment by mattansb** [comment]
I added a bootstrap method to accompany *your* commented code of computing
SEs (:

--
Mattan S. Ben-Shachar, PhD student
Department of Psychology & Zlotowski Center for Neuroscience
Ben-Gurion University of the Negev
The Developmental ERP Lab

**Comment by strengejacke** [comment]
ah ok, got it. ;-)
I think we must refactor the code, else we will have infinite loops in the bootstrap-code.

**Comment by mattansb** [comment]
I've tested it, and it should work (haven't run into any infinite loops)... But first we (you? 😅) need to finish the implementation of SE methods?

**Comment by strengejacke** [comment]
I see, `bootstrap_iterations = NA` prevents infinite loops.

> need to finish the implementation of SE methods?

There is nothing to finish - the formulas I found (and implemented so far) do not really look feasible. That's why I would only rely on bootstrapped SEs. If I understand the code correctly, there's nothing more to do (except uncommenting your lines). I will check this.

**Pull request merged**
