### PR TITLE
dev

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
I decided to further continue outsourcing the low-level and mid-level stuff of report, for which it would be more easy to focus on the verbal reporting and fanciness of tables (colours, rmarkdown compatibility etc.) 

In this context, I added a pretty-printing for `model_parmeters`. Could you guys check it out for us to discuss how it could be improved? 

Very unfortunately, I've submitted the master branch just before adding this 😕. I am still waiting for an answer from them (hence I am not merging this in case it becomes 0.1.1) but I really hope it's gonna get rejected to that the printing feature can go in...

showcase:
```r
devtools::install_github("easystats/parameters", ref="dev")
library(parameters)

model <- lm(mpg ~ wt + cyl, data = mtcars)
model_parameters(model, standardize = "refit")

library(rstanarm)
model <- stan_glm(Sepal.Length ~ Species, data = iris)
model_parameters(model, standardize = "full")
```

@strengejacke @pdwaggoner @mattansb @humanfactors @IndrajeetPatil

**Comment by DominiqueMakowski** [comment]
Great it didn't pass 😅 

```
 New submission

  Possibly mis-spelled words in DESCRIPTION:
    indices (18:168, 18:395)

  The Description field should not start with the package name,
    'This package' or similar.
```

I'll wait for this printing thing to be settled before submitting again ☺️

**Comment by mattansb** [comment]
Looks really good! Very stremlines for working in rmd!

I would change just one thing:
```R
library(parameters)
model <- lm(mpg ~ wt + cyl, data = mtcars)
model_parameters(model, standardize = "refit")
#> Parameter   | Coefficient |   SE |         95% CI |     t | DoF_residual |      p | Coefficient (std.)
#> ------------------------------------------------------------------------------------------------------
#> (Intercept) |       39.69 | 1.71 | [36.18, 43.19] | 23.14 |           29 | < .001 |               0.00
#> wt          |       -3.19 | 0.76 | [-4.74, -1.64] | -4.22 |           29 | < .001 |              -0.52
#> cyl         |       -1.51 | 0.41 | [-2.36, -0.66] | -3.64 |           29 |   .001 |              -0.45
```
`DoF_residual` to `Df residual` / `df residual`.

**Comment by DominiqueMakowski** [comment]
Right thanks, I'll change that

Maybe `DoF (residual)` or `DoF (res.)`? Or just `DoF`? 

As for switching `DoF` to `df`, this has to be voted on here 👉 #74 👈  😁

**Comment by pdwaggoner** [comment]
Looks great to me - nice printing. And I would vote for either `DoF (residual)` or just `DoF`

**Pull request merged**
